MapServer/MapServer

mapogcsld.c
Make following tests to pass : wms_get_map_sld_proj.png,
wms_get_map_multi_polygon_filter.png, wms_get_map_multi_polygon_filter_postgis.png
=> Fix post RFC91 issues in mapogcsld.c (#4974)

mapgdal.c, mapogcfilter.c, mapwfs.c
While updating the Debian package for 7.0.0-beta2, the lintian QA tool reported a couple of typos.
=> Typo fixes

mapimageio.c
DGifCloseFile has an additional parameter in giflib 5.1
=> Fix compilation with gif_lib 5.1

mapdrawgdal.c
Before, if we wanted to use the LUT with 16 bit raster, we had necessary to
use SCALE before, so as to reduce the dynamics to 8 bits, since LUT were only
supported for [0,255]->[0,255] mapping. However, for example in the case of a
12 bit raster where the desired LUT [0,4095]->[0,255] would have segments with
a width of input values < 16, it is not possible to derive a proper 8 bit LUT.
For example, let's assume we want this LUT : 0:0,15:15,4080:240,4095:255
and that the input raster dynamics is effectively [0,4095]. Once we have
rescaled to 8 bits, we cannot "convert" this 12 bit LUT into a 8 bit LUT since
it would become this degenerated LUT: 0:0,0:15,255:240,255:255
Now a LUT like 1605:30,2569:128,3372:200,4095:255 is possible.
Note that the extended LUT is only supported when SCALE is …
=> Accept LUT with input range in [0,65535] set

mapdrawgdal.c
Currently, in the absence of a BANDS processing directive,
msDrawRasterLayerGDAL() only checks that if the 4th band is the alpha
band when the raster has 4 or more bands. But for some products, the 4th
band might be the last one, so we'd better check the color interpretation
of all bands >= 4th one.
=> msDrawRasterLayerGDAL(): find alpha band even if not 4th one (#5216)

mapfile.c
=> Fix memory leak when loading FORMATOPTIONS

mapscript/python/setup.py
This fixes build with homebrew. It should probably be also applied to 6.4 and 7.0.
=> handle the case where include_dirs is set in distutils.cfg

mapdrawgdal.c
=> Fix WMS blank for classified raster with NaN, 

xmlmapfile/mapfile.xsd
moved min/maxScaleDenomentator from Layer to Style
made outlinewidth into a double
made align optional with a default of Center
fixed major whitespace issues
=> updates to schema

mapwms.c, msautotest/wxs/expected/ows_wms_rootlayer_name_capabilities.xml, msautotest/wxs/expected/ows_wms_rootlayer_name_empty_capabilities.xml, msautotest/wxs/ows_wms_rootlayer_name.map, msautotest/wxs/ows_wms_rootlayer_name_empty.map
As per #5404.  Pending consensus.
=> add metadata to optionally not emit root layer name in WMS Capabilities

mapcopy.c
=> #5483 - add copy autoangle in msCopyStyle

mapfile.c
Added the option to set a default value for variable substitution in the map's WEB section. To do that there is a new method applyHashTableDefaultSubstitutions that is being called in msApplyDefaultSubstitutions with the map's WEB section as the hash table to work on
Prior to this a 'default_<variable name>' was ignored in the map's WEB section
=> enable default value for variable substitution in map's WEB section

msautotest/misc/scaletoken.map
Unless ``DEBUG 10`` is an undocumented setting?
=> DEBUG 10 is an invalid value

msautotest/gdal/heat.map
Update to MAXSCALEDENOM in test case
=> MINSCALE and MAXSCALE are both deprecated

msautotest/renderers/embed_sb_rgba_offset.map
Remove END keyword to match documentation - see comments in #5489
=> Remove OFFSET END keyword

mapows.c, mapows.h, mapwcs.h, mapwcs20.c, msautotest/wxs/expected/wcs_20_cap_inspire_embed.xml, msautotest/wxs/expected/wcs_20_cap_inspire_embed_acceptlanguage_default.xml, msautotest/wxs/expected/wcs_20_cap_inspire_embed_acceptlanguage_multiple.xml, msautotest/wxs/expected/wcs_20_cap_inspire_embed_acceptlanguage_secondary.xml, msautotest/wxs/expected/wcs_20_cap_inspire_embed_acceptlanguage_unknown.xml, msautotest/wxs/expected/wcs_20_cap_inspire_url.xml, msautotest/wxs/expected/wcs_20_cap_inspire_url_acceptlanguage_default.xml, msautotest/wxs/expected/wcs_20_cap_inspire_url_acceptlanguage_multiple.xml, msautotest/wxs/expected/wcs_20_cap_inspire_url_acceptlanguage_secondary.xml, msautotest/wxs/expected/wcs_20_cap_inspire_url_acceptlanguage_unknown.xml, msautotest/wxs/wcs_inspire_scenario1.map, msautotest/wxs/wcs_inspire_scenario2.map
Implementation of [RFC 120](mapserver.org/development/rfc/ms-rfc-120.html)
=> RFC 120 implementation

scripts/docker/Dockerfile, scripts/docker/Dockerfile_mapcache, scripts/docker/Dockerfile_oracle_mapcache
add protocol buf support, update gdal config, add openjpeg, use c++11 (gcc 4.9)
=> bring dockerfiles up to date

mapmetadata.c, msautotest/wxs/expected/ows_metadata_layer_raster.xml, msautotest/wxs/expected/ows_metadata_layer_vector.xml
=> [WIP] :fix protocol depending on service type in ISO metadata (#5669)

mapmvt.c
Fine tuning the fix for #5731 by adding MS_ABS... --Steve
=> Make sure computed triangle height is always positive. (#5731)

mapscript/python/examples/project_csv.py, mapscript/python/examples/shpdump.py, mapscript/python/examples/shpinfo.py, mapscript/python/examples/wxs.py
=> Add shebang to Python MapScript example scripts.

mapscript/php/CMakeLists.txt
=> Install PHP MapScript.

.travis.yml
See #5779 - compile a new version of SWIG on Travis until the build server is updated.
=> Update SWIG to 3.0.12

mapogcfilter.c, mapogcfiltercommon.c
This pull request will fix issue #5741.
=> Feature names with dots are now supported for feature id filtering

msautotest/wxs/expected/wms_get_map_ext_sld_404.xml, msautotest/wxs/expected/wms_get_map_ext_sld_fileproto.xml, msautotest/wxs/expected/wms_get_map_ext_sld_proto.xml, msautotest/wxs/expected/wms_get_map_ext_sld_too_large.xml
This pull request will fix testing errors introduced by #5799. Since the error message was changed the tests which produces this error needs to be updated
=> Fix build issue introduced by #5799

mapscript/phpng/CMakeLists.txt
Address issue 5801 (hopefully)
=> add SWIG test to PHPNG cmake

.travis.yml, scripts/vagrant/packages.sh
Addressing UbuntuGIS package location changes.
=> Fixing Vagrant and Travis-CI builds.

mapscript/python/README.rst, mapscript/python/tests/cases/map_test.py
Will be backported to 7-4 branch for release
=> Update Python README.rst with latest version

mapquery.c
Reverts mapserver/mapserver#5707
=> Revert "Reduce log clutter from non-errors"

mapquery.c
Reverts mapserver/mapserver#5822
=> Re-apply "Reduce log clutter from non-errors""

mapscript/python/tests/cases/class_test.py
=> Add Python mapscript getter/setter tests for classObj

.gitattributes
Reverts mapserver/mapserver#5934
Causes binary files to see their line endings changed
=> Revert "Force LF line endings"

mappostgis.c
Fixes a performance issue dating from 7.0
The wfs_filter_postgis.map wfs_filter_postgis_property_is_equal_case_insensitive
test case exercices this code path.
=> PostGIS backend: translate insensitive equality comparison as PostgreSQL lower(foo::text) = lower('bar').

mapdraw.c, mapwms.c
Fixes a couple of issues related to query maps.
=> Backport pull-request #5920 from master to branch-7-4.

mapdraw.c
=> Add sanity checks to avoid segfaults in Mapscript pointObj::draw()

maprasterquery.c, msautotest/wxs/expected/wms_getfeatureinfo_lon_wrap_180_left_part_raster.xml, msautotest/wxs/expected/wms_getfeatureinfo_lon_wrap_180_right_part_raster.xml, msautotest/wxs/wms_getfeatureinfo_lon_wrap_180.map
Backport of https://github.com/mapserver/mapserver/pull/5969
=> [7.4 backport] GetFeatureInfo: fix for layers using a lon_wrap PROJECTION and requested in the wrapped part of the raster

mapscript/python/tests/cases/image_test.py, mapscript/python/tests/cases/point_test.py, mapscript/python/tests/cases/refcount_test.py
=> Add test for MapScript point.draw method

mapgdal.c
Fixes #5968
Derived from suggestion by @constantinius
=> WCS output / msSaveImageGDAL(): fix support of netCDF output (#5968)

appveyor.yml, mapscript/python/pymodule.i
Fix custom typemap for py3 and ensure py3 is tested in Appveyor
=> Python3 typemap fix

mappostgis.c
Fix white-space handling on function msPostGISParseData.
The DATA field contains " from\n" or similar generate invalid SQL, because '\n' don't handled as white-space
=> Fix white-space handling on mappostgis.c

README.rst
mostly a test of the new backport tool:
- create PR
- then add one of the new "backport..." labels such as "backport branch-7-6" to the PR
- when merged the bot will backport automagically to that branch
=> update README.rst urls

mapscript/swiginc/map.i
=> getRotation should be exposed to mapscript (#6048)

appveyor.yml, mapscript/python/CMakeLists.txt
This pull request runs the mapserv.exe to check it has been built successfully - otherwise the CI confusingly reports issues with Python MapScript (see #6054).
=> Run mapserv.exe in Appveyor

mapwmslayer.c
Pull-request re-done to master as requested by @jmckenna
=> Wms essential

mapwmslayer.c
- related to mapserver/mapserver#6061
- sets EXCEPTIONS to XML for essential WMS layers, specifically for the GetMap request
=> for essential WMS layers set EXCEPTIONS to XML by default

mapscript/swiginc/cluster.i, mapserver.h
Minor fixes to classObj docs and add clusterObj
=> SWIG Documentation for clusterObj

mapsymbol.c
This PR proposes a fix to issue #6079.
=> Fix wrong result on  '404 Not Found' symbol URL

mapogr.cpp
- backport bot seemed to fail for #6124 so trying to apply the changes manually to branch-7-6
=> manually apply changes through PR #6124

maptemplate.c
should be able to use the existing site's favicon, let's try..
=> add favicon to OL template

maplayer.c, mapquery.c, mapwfs.cpp
Co-authored-by: Seth G <sethg@geographika.co.uk>
=> WFS: limit SQL Select to required fields for faster data retrieval

mapmssql2008.c
wchar_t is a 4-byte int whereas SQLWCHAR is a 2-byte int...
@geographika / @szekerest  any of you want to test this on Windows  (with WITH_ICONV=ON) ?
=> mapmssql2008.c: fix warnings when building on Linux

INSTALL.CMAKE, MIGRATION_GUIDE.txt, README.rst, msautotest/README
- updates INSTALL.CMAKE version required
- updates MIGRATION_GUIDE.txt urls
- updates README.rst urls
=> Update CMake minimum version required in README

mappostgis.cpp, mapquery.c, msautotest/mspython/test_postgis.py
Follow-up to https://github.com/MapServer/MapServer/pull/5520 + extra bug fix in PostGIS backend
=> Fix bug in msQueryByFilter

.github/ISSUE_TEMPLATE.md
Largely adapted from GDAL one (which was partly inspired from QGIS one)
=> Add .github/ISSUE_TEMPLATE.md

mapfile.c
- changes by @ahermange
- regarding #6219
=> fix writeStyle(...) for "GEOMTRANSFORM CENTROID"

mapstring.cpp
Refresh of https://github.com/MapServer/MapServer/pull/5535 on top of current main
=> msGetFriBidiEncodedString(): error out on multi-line paragraph

mapogroutput.cpp
…unless wfs_geomtype is set to Polygon (fixes #6235)
=> OGR output: do not force MultiPolygon to Polygon for a TYPE POLYGON layer, 

.github/workflows/cppcheck.yml, scripts/cppcheck.sh
For now, the CI job always succeeds since we haven't cleared the backlog of issues...
=> Add a scripts/cppcheck.sh scripts and corresponding github action

mapfile.c
Possible fix for #6274
I'm unsure how much validation is/should be done on Mapfile parameters - I think this is the correct to place it though if deemed useful.
=> Ensure DEFRESOLUTION > 0

maplabel.c, msautotest/wxs/etc/fonts.txt
Fix issue raised in https://github.com/MapServer/MapServer/commit/03a96702c57cd762adc7e09b2b0decec303bd27c#r48767849
master only
=> msLoadFontSet(): fix regression of 03a9670 

.github/workflows/build.yml, .github/workflows/start.sh, ci/travis/before_install.sh, msautotest/php/classObjTest.php, msautotest/php/colorObjTest.php, msautotest/php/errorObjTest.php, msautotest/php/hashtableObjTest.php, msautotest/php/labelObjTest.php, msautotest/php/labelleaderObjTest.php, msautotest/php/layerObjTest.php, msautotest/php/lineObjTest.php, msautotest/php/mapObjTest.php, msautotest/php/owsRequestObjTest.php, msautotest/php/pointObjTest.php, msautotest/php/projectionObjTest.php, msautotest/php/queryMapObjTest.php, msautotest/php/rectObjTest.php, msautotest/php/shapeFileObjTest.php, msautotest/php/shapeObjTest.php, msautotest/php/styleObjTest.php, msautotest/php/symbolObjTest.php, msautotest/php/webObjTest.php
It strongly leverages the ci/travis script, and install packages that are already installed in Travis VM in a start.sh script
I've also done some "fixes" in msautotest/php. I suspect those tests aren't run on Travis for a unknown reason, but in the Docker image used by the github action they are run.
=> Add a github action to perform the build and tests

maphttp.c, mapserv.c, mapserv.h, mapservutil.c
Cherry-picked commits from #6304 onto main branch,
=> Use CPLSetConfigOption/CPLGetConfigOption for some CGI/FastCGI-related env vars

.github/workflows/backport.yml
- related to https://github.com/MapServer/MapServer/issues/6309
=> secure bot tokens

.github/workflows/backport.yml
- allow the backport bot to access repository 'secrets'
=> use pull_request_target to access secrets

mapshape.c, mapxbase.c
Backport of https://github.com/MapServer/MapServer/pull/6319
=> [Backport 7.6]  Fixes for several security vulnerabilities found with libFuzzer

mapserver.h
- caught through https://github.com/MapServer/MapServer/issues/6334
- credit @mrclBIE & @jratike80
=> correct LABEL->PARTIALS default value description

cgiutil.h, maperror.h, mapfile.c, mapscript/python/mapscript/__init__.py, mapscript/swiginc/label.i, mapscript/swiginc/layer.i, mapscript/swiginc/legend.i, mapscript/swiginc/map.i, mapscript/swiginc/outputformat.i, mapscript/swiginc/querymap.i, mapscript/swiginc/referencemap.i, mapserver.h
This pull request updates various MapServer functions, classes, and properties visible to SWIG generated bindings as part of [RFC 132](https://mapserver.org/id/development/rfc/ms-rfc-132.html).
=> Update doxygen docstrings

.github/workflows/backport.yml
- upgrade to recent release of `m-kuhn/backport`
- in case old version is causing problems
=> upgrade Backport github action

mappostgis.cpp
Fixes https://github.com/MapServer/MapServer/pull/6355#issuecomment-877290417
CC @sdlime
=> PostGIS: fix ST_Intersects() with collections with PostGIS < 2.5.

xmlmapfile/mapfile.xsd, xmlmapfile/mapfile.xsl
#6376 fix The "composite" is not described in the mapfile.xsl
=> The "composite" is not described in the mapfile.xsl

xmlmapfile/mapfile.xsd
=> fix Label attribute duplicate error #6379

.github/workflows/check-crlf.yml
- updates to latest release for the GitHub action, for checking line-endings
=> bump check-CRLF action

.github/workflows/irc_notify.yml
=> fix IRC action

.github/workflows/backport.yml
- includes more detailed error messages
=> upgrade Backport action

.github/workflows/backport.yml
- more improvements to backport failure case
=> bump Backport action

README.rst
=> update year in README

.github/workflows/backport.yml
=> update Backport action

mapdraw.c, mapfile.c, mapservutil.c
Addressed issues identified by @geographika and @jmckenna. Note I left style->angle check at 0 to 360.
=> Addressed issues identified in issue #6463.

mapfile.c
- reported by @stephanesaurel through #6473
=> minor fix for writing PostgreSQL JOIN through mapscript

mapscript/phpng/CMakeLists.txt
- check if SWIG version <= 4.0.2
- if yes, install the required .php constants file
=> check SWIG version for PHPNG

cmake/3.20/FindPostgreSQL.cmake
- modifies the embedded FindPostgreSQL.cmake for older CMake versions
=> find PG 14 through CMake

.github/workflows/start.sh, .travis.yml, ci/travis/before_install.sh, ci/travis/script.sh, msautotest/php/phpunit.xml, msautotest/php/run_test.sh
- also upgrades one of the test environments to the latest PHP release, 8.1.7
=> use recent PHPUnit v9 for tests

msautotest/php/colorObjTest.php
- tested today thoroughly, can't reproduce random seg faults
- fixed earlier through https://github.com/MapServer/MapServer/pull/6538
- also minor formatting fixes
=> re-enable colorObj PHPUnit tests

flatgeobuf/flatgeobuf_c.cpp, flatgeobuf/flatgeobuf_c.h, mapflatgeobuf.c
ref https://github.com/MapServer/MapServer/issues/6561
=> FlatGeobuf: Rework null geom skip

flatgeobuf/flatgeobuf_c.cpp, flatgeobuf/flatgeobuf_c.h, mapflatgeobuf.c, msautotest/misc/flatgeobuf.map
Attempt to fix https://github.com/MapServer/MapServer/issues/6554.
=> flatgeobuf: fix wkt srs

.travis.yml, msautotest/php/classObjTest.php
- spawned by https://github.com/MapServer/MapServer/issues/6582
- also upgrades one PHP build to 8.1.9
=> add PHPUnit test for createLegendIcon

mapfile.c
=> mapfile.c: add missing include to fix build issue on some compilers (fixes #6595)

etc/mapserver-sample.conf, tests/mapserver-sample.conf
- updates the note inside the distributed `mapserver-sample.conf` file
=> update MS_MAP_PATTERN required note

.travis.yml
- this will fail today, until binaries are uploaded...
=> update tests for PHP 8.1.10 release

mapdebug.c, maperror.c, maperror.h, mappostgis.cpp
Fixes https://github.com/MapServer/MapServer-private/issues/2
=> Redact password= content in msError() and msDebug() messages

mapfile.c, mapserv-config.cpp, msautotest/config/expected/missing_conf.txt
=> correct CONFIG url message

fuzzers/shapefuzzer.c
should help for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51551 and on other broken files
=> shapefuzzer: avoid too long processing time

mapshape.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51532
=> mapshape.c: avoid integer overflow in msSHPOpenVirtualFile()

fuzzers/build.sh
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52077
=> fuzzers/build.sh: build PROJ from source to avoid conflict between libstdc++ and libc++

mapfile.c
followup to https://github.com/MapServer/MapServer/pull/6651
=> Fix ossfuzz 52107

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52124
=> msLoadMap(): fix memleak in error code path related to style loading

mapproject.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52158
=> _msProcessAutoProjection(): fix memleak in error code path

mapshape.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52211
=> msSHXLoadPage(): fix integer overflow

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52222
=> loadFeaturePoints(): fix memleak in error code path

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52252
=> loadProjection(): fix memleak in case of repeated PROJECTION block

maplexer.c, maplexer.l
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52305
=> maplexer.l: fix heap-buffer-overflow issues with NUL characters

mapogr.cpp
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52363
=> msOGRShapeFromWKT(): fix memory leak in error code path

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52376
=> loadLeader(): fix memleak in error code path

mapsymbol.c
Address OSS Fuzz  issue 52410.
=> Make sure a symbol POINT block doesn't contain too many points.

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52472
=> loadProjection(): fix memleak in error code path

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52556
=> msBuildPluginLibraryPath(): fix potential memleak

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52670
=> loadGrid(): fix memleak on LABELFORMAT DD

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52702
=> loadLayer(): fix memory leak in error code path

mapfile.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53471
=> loadLayer(): fix memory leak in case of repeated CLUSTER

.github/workflows/start.sh, mapcontext.c, mapows.h, mapserver.h, mapservutil.c, msautotest/etc/mapserv.conf, msautotest/wxs/expected/ows_context_caps.xml, msautotest/wxs/ows_context.map, msautotest/wxs/ows_context.xml
=> Fix information disclosure and denial of service related to CONTEXT= loading

mapcontext.c, mapows.h, mapserver.h, mapservutil.c, msautotest/wxs/expected/ows_context_caps.xml, msautotest/wxs/ows_context.map, msautotest/wxs/ows_context.xml
Backport https://github.com/MapServer/MapServer/pull/6780
=>   [Backport branch-7-6] Fix information disclosure and denial of service related to CONTEXT= loading

LICENSE.md, README.md
- also creates a new `LICENSE.md` file
=> update markdown for README and LICENSE

flatgeobuf/include/flatbuffers/base.h
Port of upstream fix in https://github.com/google/flatbuffers/pull/7824
=> Fix build issue when abseil-cpp is present (fixes #6822)

HISTORY.md, release.sh
- easier for browsers to display
=> change HISTORY.TXT to markdown

mapagg.cpp, mapchart.c, mapdrawgdal.c, mapfile.c, mapimageio.c, mapmetadata.c, mapows.c, mapowscommon.c, mapproject.c, mapstring.cpp, mapwfslayer.c, textlayout.c
Mostly linting. Nothing critical
=> Cppcheck fixes

.github/workflows/start.sh, .travis.yml, ci/travis/after_success.sh, ci/travis/before_install.sh, ci/travis/script.sh, msautotest/php/README.md, msautotest/php/phpunit.xml, msautotest/php/run_test.sh
- update to recent CMake
- upgrade to recent PHPUnit
- remove PHP 7.4 (end-of-life)
=> update CI builds

msautotest/php/classObjTest.php, msautotest/php/phpunit.xml, msautotest/php/shapeObjTest.php, msautotest/php/styleObjTest.php
- related to changes made through https://github.com/MapServer/MapServer/issues/6852
=> update PHPUnit clone tests

mapdraw.c, maplegend.c, mapogcapi.cpp, mapogcfilter.cpp, mapogcsld.c, mapogcsos.c, mappostgis.cpp, mapprimitive.c, maptemplate.c, mapwfs.cpp
No real bugs spotted, but should help making Coverity Scan happier
=> Coverity Scan fixes

mapproject.h
Add comments to generate MapScript docs for the reprojectionObj. See https://github.com/MapServer/MapServer-documentation/issues/828
=> Add MapScript docs for the reprojectionObj

msautotest/php/owsRequestTest.php
- related to https://github.com/MapServer/MapServer/issues/6927
=> expand PHPUnit test of OWSRequest

src/mapfile.c
This should be `msTokenizeMap` not `msLoadMap`.
=> Correct error message function name

src/mapcopy.c, src/mapfile.c, src/mapogcapi.cpp, src/mapogcsld.cpp, src/mapproject.h, src/mapuvraster.c, src/mapwcs.cpp, src/mapwms.cpp
Only the [msSLDApplySLD(): fix potential memory leak or invalid free (CID 1571356)](https://github.com/MapServer/MapServer/commit/1b7b887e1d9e15de95048360c4fdb3a94e3b9a8a) commit is an actual bugfix
=> Fix various Coverity fixes warnings

msautotest/mspython/test_rq.py
Whilst looking at #6987 I made a few clean-ups. One test was not running as it doesn't have the test_ prefix, and there were also duplicate `layer.close()` calls (I presume this wasn't done deliberately?).
=> Minor Python test changes

src/mapogcapi.cpp
=> Use ows_schema_location for URLS in API response

etc/mapserver-sample.conf, msautotest/config/6968.conf, msautotest/config/6968.map, msautotest/config/expected/6968_test001.txt, msautotest/config/expected/6968_test002.txt, msautotest/query/6907_01.conf, msautotest/query/6907_01.map, msautotest/query/6907_02.map, msautotest/query/expected/6907_01_test001.txt, msautotest/query/expected/6907_01_test002.txt, msautotest/query/expected/6907_01_test003.txt, msautotest/query/expected/6907_02_test001.txt, msautotest/query/expected/6907_02_test002.txt, msautotest/query/template/6907.tmpl, src/mapquery.c, src/mapservutil.c, src/maptemplate.c, src/maptemplate.h
Fix regression detailed in #6907. Also added ability to configure things at the global level through the config file (MS_EMPTY).
=> Issues 6907 and 6968

src/mapogr.cpp
=> mapogr.cpp: do not emit some debug messages in default debug mode

mapogroutput.cpp, mapregex.c, mapregex.h, msautotest/query/expected/rfc62_test003.txt
Backport of https://github.com/MapServer/MapServer/pull/7075
=> [Backport branch-8-0] Security fixes

mapogroutput.cpp, mapregex.c, mapregex.h, msautotest/query/expected/rfc62_test003.txt
Backport of https://github.com/MapServer/MapServer/pull/7075
=> [Backport branch-7-6] Security fixes

msautotest/README
=> msautotest/README: add 20.04 requirement

src/mapscript/phpng/CMakeLists.txt
- fixes PHP MapScript for #7090
=> handle PHP out of source builds

src/mapgml.c, src/mapogcapi.cpp, src/mapows.h, src/mapwfs.cpp, src/mapwfs11.cpp, src/mapwfs20.c
=> Fix build -DWITH_OGCAPI=1 -DWITH_WFS=0

src/mapproject.c
Fixes #7019
Supersedes PR #7074
=> msProcessProjection(): strip epsgaxis= MapServer specific parameter that confuses PROJ < 9.5.0

mapparser.c, mapparser.y, mapserver.h, mapstring.cpp
=> [Backport 8.0] tostring() expression function: validate format string, and make sure buffer is large enough

mapparser.c, mapparser.y, mapserver.h, mapstring.c
Backport of PR https://github.com/MapServer/MapServer/pull/7118
=> [Backport 7.6] tostring() expression function: validate format string, and make sure buffer is large enough

SECURITY.md
@sdlime am I understanding the plan correctly? (see proposed [SECURITY.md](https://github.com/jmckenna/MapServer/blob/update-security-policy-8.2-release/SECURITY.md) for a better view)
=> Update security policy to mention 8.2 release

src/mapagg.cpp, src/renderers/agg/src/agg_font_freetype.cpp
=> Fix compilation error against FreeType 2.13.3

.github/workflows/build_alpine.sh, .github/workflows/build_alpine.yml, src/apps/map2img.c, src/mapdrawgdal.c, src/mapfile.c, src/mapio.c, src/mapobject.c, src/mapproject.c, src/maprasterquery.c, src/mapscript/swiginc/error.i, src/mapscript/swiginc/layer.i, src/mapserv-config.cpp, src/mapwcs11.cpp, src/mapwfs.cpp
=> CI: add build on Alpine edge

fuzzers/build.sh
CI fuzzer currently failing. 
See comment at https://github.com/MapServer/MapServer/pull/7218#issuecomment-2640442936
=> CI: Attempt at fixing fuzzer build

.flake8, .pre-commit-config.yaml, msautotest/pymod/msautotest_viewer.py
- recent Flake8 release has new violation code `F824` for unused variables
- recent MapServer builds, on Push, have errors such as `"global config" is unused: name is never assigned in scope`
=> CI: handle Flake8 unused variable violation code

INSTALL.CMAKE
Fix typo previously fixed in CMakeLists.txt but missed here. See #5091
=> Update Typo in INSTALL.CMAKE

msautotest/wxs/expected/wfs_200_cite_postgis_filter_or_resourceid_stringvalue.xml, msautotest/wxs/wfs_200_cite_postgis.map, src/mapogcfiltercommon.cpp
A fix for the issue in [7308](https://github.com/MapServer/MapServer/issues/7308). The explanation for the fix is found in the linked issue.
=> Fixed non numerical expressions in a getFeature request

ci/ubuntu/setup.sh
Update setup.sh to avoid manual confirmation when running script in Docker.
=> Update Ubuntu CI setup.sh
