mapimageio.c

Add OPTIMIZED=YES/NO/ARITHMETIC (default YES) format option to turn on optimized
Huffman coding.
If set to NO, use standard Huffman tables (a little bit faster in theory, but
less efficient for output size).
If set to ARITHMETIC, will use Arithmetic entropy coding instead of Huffman, for
smaller size. Note that Arithmetic coding/decoding is available in libjpeg-turbo
implementation, but not in IJG libjpeg-6b or later. So must only be used in
combinations with clients that are known to be able to decode Arithmetic encoded
JPEG.

JPEG output: enable optimized coding

---

mapwcs20.c

Fixing an issue when only the ServiceMetadata section was requested and the default outputformats were missing.

ServiceMetadata missing default formats

---

maprendering.c

MapServer will crash at very small scales, when a ttf symbol is used together with symbolscalednom, but without minsize, which is default 0.
```
MAP
SIZE 1000 500
EXTENT -90 -90 90 90
PROJECTION
"init=epsg:4326"
END
FONTSET 'glyph.fonts'
SYMBOL
NAME "test"
TYPE TRUETYPE
FONT "arial"
CHARACTER '&#97;'
END
LAYER
TYPE LINE
STATUS DEFAULT
FEATURE
POINTS
0 0
20 20
END
END
NAME 'ttflayer'
STATUS DEFAULT
PROJECTION
'init=epsg:4326'
END
SYMBOLSCALEDENOM 100
CLASS
STYLE
SYMBOL "test"
WIDTH 2
#								MINSIZE 1
END
END
END
END
```

Segfault when using ttf symbols with symbolscalednom and minsize=0

---

maprasterquery.c

With a raster query on a raster layer with 4 bands or more configured then we get a buffer overflow in msRASTERLayerGetItems().
This pull request fixes the issue.

Prevent buffer overflow with raster queries with 4 bands or more

---

mapscript/php/map.c

Calling `saveQuery` from php MapScript with result parameter set to `MS_TRUE` or `MS_FALSE`, php may segfault due to illegal assignmet of a variable parsed as long to an int variable.

Fix segfault in PHP MapScript implementation of saveQuery

---

mapdraw.c

It can sometimes be useful to flush the labelcache in the middle of map rendering for various reasons.
This pull request introduces a PROCESSING FORCE_DRAW_LABEL_CACHE directive that can be added to a layer to force rendering and flushing the labelcache after the layer is done rendering. This would typically be used on the last layer of a group of layers that should be treated as an independent group with respect to the label cache, and before starting the rendering of another set of independent layers. Setting this directive to any value triggers this behavior.
e.g.
```
LAYER
...
PROCESSING "FORCE_DRAW_LABEL_CACHE=1"
...
END

Add PROCESSING FORCE_DRAW_LABEL_CACHE layer-level directive

---

maprendering.c

I have a mapfile that has several layers that use SIZEUNITS METERS for styling the layers.  Specific to this issue is that the layers are labelled.  The text seems to be sized properly in meters, but the outline on the text is not.  It seems to always be the same no matter what value I set OUTLINEWIDTH to.
Sample mapfile: https://www.dropbox.com/s/rg9bph3awkmujr2/outlinewidth.map?dl=0
This seems to have started happening after the fix for #4942.
I checked out 3e7ecf7d1ca3512c6c66f30ebed739cdd484a841, and the problem did not happen, but checking out d0043f27538ff70c7911fa22707d4839ccfeae80 makes it happen.  It also happens with an up-to-date branch-7-0

Label outline not changing when OUTLINEWIDTH value changed

---

mapscript/php/color.c
mapscript/swiginc/color.i

Changes in the SWIG bindings:
- add the methods setRGBA() and toHexWithAlpha()
- extend the method setHex() to accept #rrggbbaa hex values
Changes in the PHP bindings:
- add the methods setRGBA() and toHexWithAlpha()
- adds the methods toHex() and setHex() which were already in the SWIG bindings
Fix for #5077 
Still TODO:
- PR to update documentation
- Tests?

MapScript colorObj SWIG/PHP alignment and methods with alpha

---

maptemplate.c

Due to these parts being processed in BROWSE mode, no layer metadata
could be accessed - this commit allows access to layer metadata tags
so long as there is a current (non-null) resultlayer, regardless of the
mode in which processLine() is being run

Allow access to layer [metadata_*] tags in legacy headers & footers

---

mapstring.c

The function msLayerEncodeSahpeAttributes calls iconv_open in mapstring.c, line 2206 even if iconv is not being used.  The #ifdef USE_ICONV  block maybe should extend through the entire function instead of ending at line 2201 with a new ifdef USE_ICONV block starting at line 2213?

Compiling without iconv fails.

---

maputil.c

A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
- https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
- https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.

Cleaning up conditional directives that split up parts of statements.

---

mapscript/mapscript.i
mapscript/swiginc/map.i

SWIGWIN hashdef is not defined when building c# windows mapscript,
(contrary to what swig 1.3 documentation says)
so WIN32 hashdef is used instead

using defined(WIN32) for c# windows mapscript specific

---

maplayer.c

My WFS request is the following code:
```
<?xml version='1.0' encoding='UTF-8'?>
<wfs:GetFeature  service='WFS' version='1.0.0' 
xmlns:wfs='http://www.opengis.net/wfs' 
xmlns:gml='http://www.opengis.net/gml' 
xmlns:ogc='http://www.opengis.net/ogc' 
xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
xsi:schemaLocation='http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.0.0/wfs.xsd'>           
<wfs:Query typeName='district' srsName='EPSG:3830'>
<ogc:Filter>
<ogc:PropertyIsEqualTo>
<ogc:PropertyName>TField</ogc:PropertyName>
<ogc:Literal>高新区</ogc:Literal>
</ogc:PropertyIsEqualTo>
</ogc:Filter>
</wfs:Query>
</wfs:GetFeature>
```
I want to search the feature that the value of field named TField is 高新区. I set the the layer's encoding to GBK, ant the above request returns the …

WFS request with chinese keywords does not have any result

---

mapfile.c

I'm forwarding the patch by Michael Tautschnig, as reported in [Debian Bug #812685](https://bugs.debian.org/812685):
> During a rebuild of all Debian packages in a clean sid chroot (using cowbuilder
and pbuilder) the build failed with the following error. Please note that we
use our research compiler tool-chain (using tools from the cbmc package), which
permits extended reporting on type inconsistencies at link time.
> 
> ```
> mapfile.c line 65: error: conflicting types for variable `msyystring_icase'
> old definition in module `maplexer' file maplexer.l line 51
> signed int
> new definition in module `mapfile' file mapfile.c line 65
> char
> ```
> 
> Depending on endianness of the platform, the lexer may use the wrong byte of
msyystring_icase. The attached patch fixes this problem.
The …

Fix type inconsistencies.

---

maplabel.c

It seems as if there is a border problem when masking out labelled layers. Sometimes labels at the very edge of the map leak through even when they should definitely be masked away.
Example:
Input dataset:
The above dataset masked with a mask which is a union of the polygons at the centre of the map:
Geometries are correctly masked, but note the label "Nørre Broby".
Using v6.4.1

Labels leak through MASK

---

mapdraw.c

Using current master branch, I am having trouble manually drawing points with text on a map when `LABELCACHE OFF`.  I do have better luck, but sometimes crashes with `LABELCACHE ON`.  I am attaching a reproducer for me.
[ms.zip](https://github.com/mapserver/mapserver/files/128737/ms.zip)
```
$ php l.php
php: /home/akrherz/BUILD/mapserver/maprendering.c:998: msDrawTextSymbol: Assertion `ts->textpath' failed.
Aborted (core dumped)
```
If I enable LABELCACHE, I get this
This was working for me with PHP mapscript 6.4.  My environment is RedHat 7.2 64bit, thanks

PHP Mapscript maprendering.c:998: msDrawTextSymbol: Assertion `ts->textpath' failed

---

maputil.c

It seems that each list item is compared to the string attribute item but it is not checked if it is the whole string. 
```
CLASSITEM 'event'  
EXPRESSION {rain,drizzle}
```
This expression above returns true if "event" string  attribute = "freezing rain"
A user suggested this fix
From  https://github.com/mapserver/mapserver/blob/157fa474ff8748ec42652f49dc4e2be4ca89042e/maputil.c#L490
Line 490 should probably read:
if(!strncmp(start,shape->values[itemindex],end-start) && shape->values[itemindex][end-start] == '\0') return MS_TRUE;
Here are other examples where Expression returns true, but might not be the same problem/solution
```
String=freezing rain
EXPRESSION {rain,freezing drizzle} #doc says no space should be used though
```
```
String=freezing rain
EXPRESSION {rain,freezing,drizzle} …
```

Layer class LIST Expression

---

apache/mod_mapserver.c

Build fails when built with -Werror=format-security

Correct compile error with -Werror=format-security

---

mapgeomtransform.c
maplegend.c

This should fix issue #5193. If OK, it should be applied to the 6.4 and 7.0 branches. --Steve

Fixed case when drawing legend shapes with style geomtransforms. (#5193)

---

mapogroutput.c

When using GeoJSON as output format with the OGR GeoJSON driver, an empty response (`Content-Length: 0`) is returned when no features match a query.
For GML an empty feature collection is returned, I would expect the same for GeoJSON. GeoServer does it this way and OpenLayers 3 also expects an empty feature collection.

Empty response is returned for GeoJSON when no features

---

mapfile.c

If I set a min or max scale in Mapscript (python) using
```
k.maxscaledenom = 5000000000.0
```
And then generate the mapfile using
```
m.save()
```
The resulting value is formatted as:
```
MAXSCALEDENOM 5e+09
```
Which means the annotation layer isn't rendered until I replace it with:
```
MAXSCALEDENOM 5000000000
```
Is there anyway to control the format of these values when using save()?
Thanks

Min/Max scale values incorrectly formatted (python Mapscript)

---

maputfgrid.cpp

I use Mapserver 7.0.1 (and also tried the latest master) and wasn’t able to get any output from the web-Service as WMS-Request with format “application/json”.
The application/json-response has a filesize of 0Bytes, other formats (jpeg/png) work well – with exactly the same request, except the format.
UTF-Grid also seems to be produced well with a simulated request against mapserver on the commandline-interface
(“/usr/local/bin/mapserv QUERY_STRING="SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=339444,5697190,347678,5702286&CRS=EPSG:25832&WIDTH=1556&HEIGHT=963&LAYERS=poi &STYLES=&FORMAT=application/json&TRANSPARENT=TRUE&map=PATH_TO_MAPFILE" > OUTPUT”)
Mapserver LOG (DEBUG 5) with above request wms request thru Apache webserver (**fcgi**-mode):
[Thu Mar  3 17:01:37 2016].53153 CGI Request 3 …

UTF-Grid not working in .fcgi-mode

---

mapmssql2008.c

See notes at https://msdn.microsoft.com/en-us/library/ms716287(v=vs.85).aspx
I'm not sure how this would affect MapServer on pre Windows 2003 builds. Hopefully someone can review the implications.

Update to new ODBC types SQLLEN and SQLULEN to fix issue #5172

---

scripts/docker/Dockerfile

This adds a basic but fairly complete docker build file of gdal and mapserver and apache. Can be used for setting up docker hub automated builds of MapServer.

Add basic dockerfile for automated builds

---

mappostgis.c

In PostGIS filter, a MS_TOKEN_COMPARISON_EQ followed by a MS_TOKEN_LITERAL_TIME is ignored, because the operator if set with the MS_TOKEN_LITERAL_TIME.
Fix #5265

Fix filter of MS_TOKEN_LITERAL_TIME in PostGIS (#5265)

---

mapmssql2008.c
mappostgis.c

Triggered by Jeff's 7.0.2 maintenance release announcement, it's high time to forward this patch upstream.
The spelling error was reported by the lintian QA tool for the Debian package build.

Fix "didnt" typo, replace with "didn't".

---

mappostgis.c

Some arcs end up drawn as full circle. See the center of the attached image, the red circle.
test-data, same eâs shown in image (sql dump) can be found here:
www.tydac.ch/download/compound_test.zip

Issue rendering compound polygons (PostGIS)

---

mapcairo.c

Non-square SVG symbols are clipped when they are rotated.
Here is an example where a small box of 40x20 pixel is rotated by 45 and 90 degrees:
Here is the Mapfile and SVG symbol:
https://gist.github.com/olt/2a345fe22653cd021c29
Tested this with current master, 7.0.1 and 6.4.3 (`shp2img -m clipped-symbol.map -o out.png`).

SVG symbol gets clipped when rotated

---

mapogcfiltercommon.c
msautotest/wxs/expected/wfs_filter_false_ogr_property_is_equal_and_bbox.xml
msautotest/wxs/wfs_filter.map

A <Filter><And>....<BBOX></BBOX></And></Filter> results in
a ( ..... ANDintersects(....)) mapserver expression. The expression lexer seems
to make sense of it though, but this is ugly.

Filters: add whitespace between and and next part (relates to #5352)

---

mapogr.cpp

Error messages created by the OGR driver may leak too much information. See http://gis.stackexchange.com/questions/219426/mapserver-hide-ogr-exception
Same issue as #4928 but for OGR

OGR error messages too verbose

---

maporaclespatial.c

If the memory area pointed by `table_name` is too small, it is resized multiplying its size by 2. But if this occurs, the `tgt` variable used in the "for" loop continues to point on a memory area which might have become invalid (because the realloc could have moved the memory somewhere else, depending on how the OS manages the memory).
To fix this, in my understanding, the `tgt` pointer should be readjusted after the realloc call to the new location pointed by `table_name`.
Running valgrind without my patch (sources based on the 7.0.1 version, but the maporaclespatial.c is identical to master):
```
==1908== Invalid write of size 1
==1908==    at 0x4E81FEF: msSplitData (in /usr/lib/x86_64-linux-gnu/libmapserver.so.7.0.1)
```
Running in gdb gives the following error:
```
*** Error in …
```

oracle - fixing memory handling error

---

mapscript/csharp/CMakeLists.txt

Fixes the name of the C# module.  Should be `mapscript.dll` however the generated code currently looks for `csharpmapscript.dll` so will throw an error when loaded.
Seems it's only the cmake file that has this result.
@szekerest thoughts?

Fix generated C# module

---

mapwms.c

If LAYERS is specified multiple times in the query string, nLayerOrder isnt
reset to 0, and this leads to memory corruption/double-free's upon exit.

Declare nLayerOrder where it's used. (#5387)

---

CMakeLists.txt
version.rc.in

This commits adds a version stamp to the mapserver.dll on Windows like the following: Just a nice touch more than anything else.

Add dll version stamp in Windows

---

mapquery.c

The msQueryByFilter() function disabled paging (and also max features) by default which could cause serious performance issues when you only want a feature or two from a large result set.
Steve

Allow paging in msQueryByFilter().

---

mapogcsld.c

Previously, the subtree of the <Graphic> tag from the SYMBOL type MS_SYMBOL_SVG was not generated in the sld-file.
Fixed formatting error in snprintf.

Forming the tag <OnlineResource> in the sld-file from the SYMBOL type MS_SYMBOL_SVG

---

msautotest/wxs/wfs_filter_postgis.map

#5202 : WFS Intersects filters are limited by the extent defined in the mapfile. I added 2 tests that play with the extent of the map to return no results and 2 results.

Add two tests to cover the out-of-extent intersects filter

---

mapresample.c

https://github.com/mapserver/mapserver/commit/026847b1c962cdd666d28cfbe38ac40fff54ffbb
introduced a post correction of the source geotransform so that it matches the
sSrcExtent exactly. However the condition for this to make sense is that the
initial geotransform has square pixels.

msResampleGDALToMap(): restrict fix done for #1715, to avoid regressions like #5445

---

maporaclespatial.c

Fix error to support Oracle compound elements for GTYPE 2007 (multipolygon) and not only for GTYPE 2003 (polygon)

Fix error to support Oracle compound elements for GTYPE 2007

---

msautotest/misc/runtime_sub.map

Otherwise all these tests fail on Windows as the command isn't split properly and results in errors such as:
`'name1' is not recognized as an internal or external command,operable program or batch file.`
The change to double quotes shouldn't affect Linux as I understand it.

Change to double quotes for Window's command line parameters

---

mapscript/csharp/CMakeLists.txt

this fix allows to have an out-of-source build on any location - previously it was assumed that the mapscript csharp sources had a fixed path relative to the build
In addition we can now have build path names with spaces

Fix enable out of source build path with spaces

---

maplayer.c

Enabled WFS sortby for Oracle plugin, Previously that was only available if Oracle support was statically linked to mapserver.
additionally we now support a quoted sortby parameter to enable sorting by non-capitalized column names

Enabled WFS sortby for Oracle plugin

---

maporaclespatial.c

Removed bug that caused MapServer only to use the Oracle TranslateFilter method at the first call e.g. in an FCGI environment
unlike all other vtable assignments the msOracleSpatialLayerTranslateFilter was set to layer->vtable and not to vtable
The effect was that e.g a WFS filter was only translated to the SQL statement in the first call, in all subsequent calls the original SQL statement was used and the filtering was done by MapServer after the fetch - for large datasets that caused significant overhead

Fix bug in Oracle TranslateFilter method 

---

maporaclespatial.c

Adding double quotes to the columns of the mapserver generated outer
query safely allows using double quoted column aliases in the data
statement
By that we can have mixed capital column names

Allow using double quoted aliases for Oracle column aliases

---

maplayer.c
maporaclespatial.c

This is to clean up some stuff from pull request #5454 - see newest comments there
commented out vtable entries for msOracleSpatialEscapePropertyName.
By that we don't need the additional logic described below anymore
Revert "Enclose the sortby property in double quotes by putting the result of  msLayerEscapePropertyName into double quotes"
This reverts commit d5f89a3353854b0f6a8eda0758d99e74372fdf9f.

Proper escaping of Oracle sortby parameters - Enhancement for pull request #5454

---

mapresample.c

Repeat transformation for a rectangle interior to the output requested region. If the latter results in a more extreme y extent, then extend extents in source layer projection to southern/northing bounds and entire x extent. This fix resolves issue #4864.

Repeat transformation if extent is extreme

---

mapprimitive.c

longest_line_index can point outside pll->ll if shape only contains
lines with <2 points.
This can segfault here: https://github.com/mapserver/mapserver/blob/c6abf4224e6a1429869b9ee7c7a72dd791f74eb3/mapprimitive.c#L1821-L1822
I'm unable to create a minimal mapfile as WKT and POINT features do not support broken MultiLineStrings.
However, msPolylineComputeLineSegments does already expect lines with <2 points.
https://github.com/mapserver/mapserver/blob/c6abf4224e6a1429869b9ee7c7a72dd791f74eb3/mapprimitive.c#L1584

Fix segfault with polyline labels for empty (multi)linestrings

---

mapmssql2008.c

This WFS filter 
`<Filter>
<AND>
<PropertyIsEqualTo><PropertyName>Status</PropertyName><Literal>Open</Literal></PropertyIsEqualTo>
<BBOX><Box srsName='EPSG:3857'><coordinates>...</coordinates></Box></BBOX>
</AND>
</Filter>`
generates this TSQL query : 
`WHERE ((Geography.STIntersects(geography::STGeomFromText('POLYGON ((...))', 4326)) = 1.000000 AND ([Status] = 'Open'))) and Geography.STIntersects(geography::STGeomFromText('POLYGON((...))',4326)) = 1 `
The `1.000000` seems harmless but causes a big performance issue. In my case, the SQL spatial index is not used. 
This PR generates the following TSQL query and solves the issue.
`WHERE ((Geography.STIntersects(geography::STGeomFromText('POLYGON ((...))', 4326)) = 1 AND ([Status] = 'Open'))) and …

Fix MSSql query generator when using filters with multiple parameters

---

mapscript/java/CMakeLists.txt

The lintian QA tool reported that the mapscript.jar contains source (in addition to the compiled .class) files.
The java files should not be included along with the .class files.

Exclude .java files from jar.

---

mappostgis.c

msPostGISBuildSQLWhere: quote the geo column name

---

mapstring.c

I guess I must have missed this in the original pull request. This was a fix supplied by @tbonfort and relates to this - https://github.com/mapserver/mapserver/pull/5277
This pull request includes the code from https://github.com/tbonfort/mapserver/commit/bacf44f24a2dab8eff47d98788a302b7e0b0bb49
If strdup is used on Windows/MSVC then char variables don't get set correctly (at least when using the debugger).

Use strcpy rather than strdup

---

README.rst

In preparation for the 7.2 release, would it be worthwhile changing the README to an RST file so it is nicely formatted on GitHub? You can see a preview at https://github.com/geographika/mapserver/tree/7-2-readme
As the default branch in GitHub will be 7.2 until the next major release I created the pull request against the 7.2 branch. I can make it against master if preferable. 
I added in the status button of the master build from Travis. 
I can also add in Appveyor, but it seems like you need to be an admin to see the URL for the badge. @sdlime - if you get a chance maybe you could add me as an admin to the Appveyor MapServer project, similar to MapCache?

Use RST for ReadMe

---

mapscript/python/pymodule.i
mapscript/python/tests/cases/hashtest.py

Supersedes #5614
Add various Python methods so that a hashtable can be used like a dict. See #5582 for background. 
API is now as follows:
```python
import mapscript
ht = mapscript.hashTableObj()
ht["key1"] = "value1"
ht["key2"] = "value2"
ht["key3"] = "value3"
ht["key4"] = "value4"
del ht["key1"]
print(ht.keys)
print(len(ht))
print("k1" in ht)
print(len(ht))
```
Or for a more concrete example:
```python
print(map.web.metadata.keys()) # ['wms_srs', 'ows_enable_request', 'ows_http_max_age']
print(map.web.metadata["wms_srs"]) # EPSG:4326
map.web.metadata["wms_srs"] = "EPSG:2157"
print(map.web.metadata["wms_srs"])  # EPSG:2157
```

Add Python methods to hashtable so it can be used like a dict

---

mapxbase.c

Latest GCC shows these warnings when compiling release build:
warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
warning: ‘strncpy’ output may be truncated copying between 0 and 39 bytes from a string of length 39 [-Wstringop-truncation]
warning: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
In msDBFWriteAttribute we can replace strncpy with memcpy since we already check for the string length and we don't want the strncpy capability of writing extra \0 characters.
Also replace the 2 snprintf calls (one for the specific format, and one for the value) with a single one.
As snprintf can handle 0 precision numbers just fine, we don't need a separate branch for that …

Simplify msDBFWriteAttribute to get rid of compiler warnings

---

mapwms.c

Compiler warned about misleading indent for commit c8190e5f3d27f0d93648c6fa7e7c6671ce729402

mapwms: fix forgotten if braces

---

mapogcsld.c

Fix potential overflow when writing hexcolor in the unlikely case color components are bigger than 255. Just keeping the compiler happy.

mapogcsld: fix potential overflow when writing hexcolor 

---

mapmvt.c

Stupid error meant no single point features escaped clipping. --Steve

Fixed clipping error for point layers (#5652).

---

mapwcs.c
mapwcs20.c

Mostly to keep the compiler happy and stop complaining.

mapwcs: fixes to uninitialized memory / snprintf

---

appveyor.yml
mapscript/csharp/csmodule.i
mapscript/csharp/swig_csharp_extensions.i

See https://github.com/mapserver/mapserver/issues/5575
This initial pull request brings the number of errors when building with SWIG 3.0.12 from `1592 Error(s)` to`8 Error(s)`.
The remaining errors are:
```
[00:02:38]   mapscript.cs(25,58): error CS0234: The type or namespace name 'EntryPoint' does not exist in the namespace 'System.Runtime.InteropServices' (are you missing an assembly reference?) [C:\projects\mapserver\build\mapscript\csharp\mapscript.vcxproj]
[00:02:38]   mapscript.cs(25,4): error CS1729: 'DllImportAttribute' does not contain a constructor that takes 2 arguments [C:\projects\mapserver\build\mapscript\csharp\mapscript.vcxproj]
[00:02:38]   mapscriptPINVOKE.cs(191,10): error CS0111: Type 'mapscriptPINVOKE' already defines a member called '.cctor' with the same parameter …
```

Update C# bindings to work with SWIG 3.x

---

mapwms.c

New pull request targeting branch-7-2 instead of master.
If the WMS filter parameter is empty (e.g. FILTER=) you will get a 500 error. This pull request changes this behavior so that it will instead ignore empty filters.
See discussion in #5597 for more details.

Silently ignore WMS filter if the provided value is empty

---

maptemplate.c

There is a built-in OpenLayers viewer in Mapserver which uses http://www.mapserver.org/lib/OpenLayers-ms60.js as URL to OpenLayer.
I was able to use this over https only if i tell my browser to allow mixed-content.
This patch changes the url to be a protocol relative URL. This causes Firefox to use https even if i call the viewer via http.
I tested and it works a little bit better now, because there are still http://-urls to the images in OpenLayers-ms60.js:
If you merge this and anyone changes OpenLayers-ms60.js on your homepage to do the same, users can use the built-in OpenLayers viewer over https out-of-the box.
Thank you.
Alex

Change URL to OpenLayers to be protocol relative

---

mapmetadata.c
msautotest/wxs/expected/ows_metadata_layer_raster.xml
msautotest/wxs/expected/ows_metadata_layer_vector.xml

emit only required formats for WMS links in ISO metadata (#5667)

---

CMakeLists.txt

See #5700 - this hides the most frequent lower level warnings, so more significant issues can be addressed. 
It brings the warnings down from ~830 to ~50.

Hide MSVC compiler warnings

---

mapscript/mapscript.i

Prevent Python mapscript from rebuilding every time due to possible CMake/SWIG bug. See #5708

Fix Python MapScript Rebuilding

---

CMakeLists.txt
cmake/FindPythonModule.cmake
mapscript/mapscript.i
mapscript/python/CMakeLists.txt
mapscript/python/README.rst

This pull request modifies how the `make install` command install the Python MapScript bindings. Currently CMake simply copies the _mapscript.so and mapscript.py files to `/usr/local/lib/python2.7/dist-packages/`
This update uses CMake to run `python setup.py install` if `make install` is run. This creates installation metadata and copies it to `/usr/local/lib/python2.7/dist-packages/mapscript-7.3.0-py2.7-linux-x86_64.egg/`
This should allow other applications that rely on MapScript to check if the dependency is already installed, and to allow MapScript to be listed and uninstalled using pip. It hopefully also helps with packaging Python MapScript in the future and addresses #5140. 
The new MapScript installation also includes the tests and examples within the MapScript module - the same …

Python MapScript install

---

CMakeLists.txt

Compiler flags are MSVC specific rather than just Windows, so check for this.

Check for MSVC rather than WIN32 when setting compiler flags

---

.gitignore
.travis.yml
Makefile
mapscript/csharp/CMakeLists.txt
mapscript/csharp/csmodule.i
mapscript/csharp/run_test.sh
mapscript/csharp/swig_csharp_extensions.i

In reference to
http://osgeo-org.1560.x6.nabble.com/csharp-mapscript-dotnet-core-on-Linux-td5391329.html
and
#5728
##sample usage:
$ mkdir build
$ cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/opt
-DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu:/usr/share/postgresql/10:/usr/local:/opt
-DWITH_CLIENT_WFS=ON
-DWITH_CLIENT_WMS=ON
-DWITH_CURL=ON
-DWITH_SOS=ON
-DWITH_PHP=OFF
-DWITH_PERL=OFF
-DWITH_RUBY=OFF
-DWITH_JAVA=OFF
-DWITH_CSHARP=ON
-DWITH_PYTHON=OFF
-DWITH_SVGCAIRO=OFF
-DWITH_ORACLESPATIAL=OFF
-DWITH_MSSQL2008=OFF
../ >../configure.out.txt
$ make mapscript

mapscript_csharp compilable on Linux

---

mapkmlrenderer.cpp

The lintian QA tool reported a spelling error for MapServer 7.4.0-beta1:
* sould -> should

Fix spelling errors

---

mapscript/phpng/CMakeLists.txt

Enabling PHPNG causes the configure target to fail because the `PHP_FOUND_INCLUDE_PATH` is used instead of `PHP_INCLUDE_PATH` as set by `find_package(PHP)`.

Fix variables set by find_package(PHP).

---

mapproject.c

This pull request will solve reprojection issues in certain edge cases. 
Not all geometries of the shapefile I was rendering appeared in the final image even though the extent cover all geometries. When I found the issue I had the following setup:
- Shapefile with data in EPSG:32633 projection
- WMS request with bounding box specified in EPSG:4326 projection
- The following query string was used to debug the issue:
```QUERY_STRING=map=fylker.map&FORMAT=image%2Fpng&LAYERS=Fylker_Norge_flate&TRANSPARENT=TRUE&VERSION=1.3.0&EXCEPTIONS=INIMAGE&SERVICE=WMS&REQUEST=GetMap&STYLES=&CRS=EPSG%3A4326&BBOX=-90,-180,112.92325084041,22.92325084041&WIDTH=512&HEIGHT=512```
When the bounding box is reprojected (-90,-180,112.92325084041,22.92325084041) to EPSG:32633 the reprojected bounding box will not be …

Add sampling along diagonal for rectangle as polygon reprojection

---

mapgml.c
msautotest/wxs/expected/wms_getfeatureinfo_encoding.xml
msautotest/wxs/wms_getfeatureinfo_encoding.map

GML:Name is now encoded in WMS GetFeatureInfo (fixes #5361)

---

mapogcsld.c

This PR fixes an error message that requests `TMPPATH` be set in the mapfile, when the correct parameter name is `TEMPPATH`.

Fix reference to TEMPPATH in SLD error message

---

renderers/mvt/vector_tile.proto

This removes the warning thrown with protobuf 3, when compiling MapServer:
```
[libprotobuf WARNING D:\protobuf-3.6.1\src\google\protobuf\compiler\parser.cc:562] No syntax specified for the proto file: vector_tile.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
```

set required syntax statement for protobuf 3 (#5376)

---

mapscript/python/tests/cases/map_test.py

To fix #5817
> the WKT string is invalid. It lacks a GEOGCS node. Previous versions of GDAL were too lax regarding this. You could instead use the following for example

Update Projection WKT string

---

mapquery.c

Prevent "No matching records" from filling up logfile in terse mode.
https://github.com/mapserver/mapserver/issues/5706

Reduce log clutter from non-errors

---

cmake/FindOracle.cmake

Added version specific libnnz name to the ORACLE_NNZ_NAMES list

Issue #5796 - Latest OCI library files not found

---

msautotest/misc/ogr_empty_geojson.map
msautotest/wxs/wfs_200.map
msautotest/wxs/wfs_200_allgeoms.map
msautotest/wxs/wfs_200_cite.map
msautotest/wxs/wfs_200_cite_postgis.map
msautotest/wxs/wfs_200_low_wfsmaxfeatures_no_compute_number_matched.map
msautotest/wxs/wfs_filter.map
msautotest/wxs/wfs_filter_ogr.map
msautotest/wxs/wfs_filter_postgis.map
msautotest/wxs/wfs_filter_projmeter.map
msautotest/wxs/wfs_ogr_native_sql.map
msautotest/wxs/wfs_ogr_no_native_sql.map
msautotest/wxs/wfs_time.map
msautotest/wxs/wfs_time_ogr.map
msautotest/wxs/wfs_time_postgis.map
msautotest/wxs/wms_inspire.map
msautotest/wxs/wms_raster.map

Following #5707, some msautotests failed. These tests expected error messages that were filtered out by said PR. The proposed update increases the debug level to 3 on impacted layers in msautotests, so that expected error messages are produced.

Add 'DEBUG 3' on failing msautotests

---

mapmssql2008.c

@geographika I believe this should do it, but couldn't test. I'd appreciate if you could report if it solves your issue
We should probably add mssql tests in msautotest. Relevant snippets from GDAL autotest suite: https://github.com/OSGeo/gdal/blob/master/gdal/ci/travis/ubuntu_1604/before_install.sh#L10 and https://github.com/OSGeo/gdal/blob/master/gdal/ci/travis/ubuntu_1604/before_install.sh#L46

MSSQL2008: deal with termination '$' at end of regular expression. Follow-up of eea166a5157d4742b617cd7561c62cd2df5c8f5c (refs #5825)

---

mapscript/phpng/CMakeLists.txt

Added block of code defining -undefined dynamic_lookup for a LINK_FLAG to fix Undefined symbols for architecture x86_64: error when compiling.  Code block was taken directly from the CMakeLists.txt file located in the mapscript/php directory.

Fix Undefined symbols compile error on macOS.

---

mapgdal.c
mapmetadata.c
mapogroutput.c
mapquery.c
mapscript/php/mapscript_i.c
mapscript/php/php_mapscript.c
mapscript/php/php_mapscript.h
mapscript/python/pyextend.i
msautotest/misc/ogr_empty_geojson.map
msautotest/wxs/wfs_200.map
msautotest/wxs/wfs_200_allgeoms.map
msautotest/wxs/wfs_200_cite.map
msautotest/wxs/wfs_200_cite_postgis.map
msautotest/wxs/wfs_200_low_wfsmaxfeatures_no_compute_number_matched.map
msautotest/wxs/wfs_filter.map
msautotest/wxs/wfs_filter_ogr.map
msautotest/wxs/wfs_filter_postgis.map
msautotest/wxs/wfs_filter_projmeter.map
msautotest/wxs/wfs_ogr_native_sql.map
msautotest/wxs/wfs_ogr_no_native_sql.map
msautotest/wxs/wfs_time.map
msautotest/wxs/wfs_time_ogr.map
msautotest/wxs/wfs_time_postgis.map
msautotest/wxs/wms_inspire.map
msautotest/wxs/wms_raster.map
renderers/agg/include/agg_conv_curve.h
renderers/agg/include/agg_path_storage.h

Mostly boring compiler warning fixes, but there were interesting issues
in mapquery.c function where the emission of msSetError(MS_NOTFOUND, )
depended on lp->debug >= MS_DEBUGLEVEL_V, which seems inappropriate,
as a few mapfiles actually needed to have DEBUG 3 in their LAYER definition.
Just always emit the error.

Assorted set of compiler warning fixes, and remove need for DEBUG 3

---

mapmssql2008.c

These calls as disable spatial indexes causing a performance hit. 
See post in [mailing list](https://lists.osgeo.org/pipermail/mapserver-users/2019-September/081380.html).

Remove MakeValid() from MSSQL Driver

---

maplexer.c
maplexer.l

The latest regeneration of maplexer.c with a more recent version of flex
caused isatty() to be called, which caused a warning when building on Windows.
Parsing from an interactive terminal is not a use case for mapserver, so
add `%option never-interactive`.

maplexer.l: avoid warning about isatty() on Windows

---

appveyor.yml

Currently getting lots of timeouts from sourceforge.net

Cache SWIG 3.0.12

---

mapscript/python/pymodule.i
mapscript/python/tests/cases/map_test.py
mapscript/swiginc/layer.i
mapscript/swiginc/map.i

This pull request adds a `applyDefaultSubstitutions` function to all SWIG MapScripts, and an `applySubstitutions` function to Python MapScript along with an appropriate typemap. 
Usage is as follows - `applyDefaultSubstitutions` can be called directly on a mabObj:
```python
s = """
MAP
WEB
VALIDATION
'key1' '.*'
'default_key1' 'Test Title'
END
METADATA
"wms_title" "%key1%"
END
END
END
"""
map = mapscript.fromstring(s)
map.applyDefaultSubstitutions()
```
`applySubstitutions` can be used in Python by supplying a dict of keys and values (both need to be strings) to replace any variables in a Mapfile. 
```python
s = """
MAP
WEB
VALIDATION
'key1' '.*'
'default_key1' 'Test Title'
END
METADATA
"wms_title" "%key1%"
END
END
LAYER
TYPE POINT
FILTER ([size]<%my_filter%)
VALIDATION
'my_filter' …
```

Add runsub MapScript functions

---

mapgdal.c
mapserver.h
mapwmslayer.c

The function didn't remove the temporary files, mostly when
saving an image through GDAL in /vsimem/msout
This would result in memory usage and execution time for repeated
requests in the same process to grow linearly with the number of
requests, instead of remaining constant.

CleanVSIDir: make it actually work (memory usage and perf fix)

---

mapscript/mapscript.i

Currently when compiling with MSVC on Windows using `-DWITH_PYTHON=1` and in DEBUG the following error occurs:
`LINK : fatal error LNK1104: cannot open file 'python27_d.lib`
To resolve this would require compiling Python from scratch. Ideally we want to be able to create a DEBUG release of MapServer with Python, but don't require Python itself to be in DEBUG mode. 
SWIG has an option to avoid this as [documented here](http://www.swig.org/Doc4.0/Python.html#Python_nn12)
See also https://stackoverflow.com/a/32631330/179520

Don't set Python debug lib on Windows

---

maptemplate.c
msautotest/query/expected/query_test013.txt
msautotest/query/query.map
msautotest/query/template/query_formatted.tmpl

See #5889 - adds a new "padding" format option for fixed length strings in a template. 
Online testing in REPL at https://repl.it/repls/LeftSlimQuotient
Reviews of C code welcome, especially if variable declarations should be moved, and everything is created and freed correctly.

Add a new padding template format option

---

mapwcs.c

When a WCS 1.0.0 GetCapabilities reply is made, a single failing layer (e.g. a wrong file name/path) will cause MapServer to truncate output of Capabilities document and list only thus far processed valid layers. This is strange choice as there is no error generated to indicate a failure and at the same time produced Capabilities document does not contain all valid layers. Thus the change causes Capabilities generator to just skip bad layer and continue with remaining layers.

WCS 1.0.0 server: Skip broken layers instead of a complete failure.

---

mapfile.c
mapstring.c
msautotest/misc/expected/runtime_sub_test_caps.xml
msautotest/misc/runtime_sub.map

See #5895
* Pull request changes `strncmp` to `strncasecmp` in the relevant checks of "default_"
* Adds a new test and results using DEFAULT_
* Fixes a couple of typos in a string function comment
Can be squashed before merging.

Make default_ in VALIDATION block case insensitive

---

mapthread.c

Revert partly https://github.com/mapserver/mapserver/commit/ba3d172764b6901c60e93eb4b51d2c17813161c1
Credits to @geographika for bisecting down to that commit.

msGetThreadId(): fix for Windows

---

mapscript/python/tests/cases/cluster_test.py

clusterObj tests for Python MapScript. 
Cherrypicked from #5870 - which has become too out-of-date to rebase easily. I'll break this down into smaller more logical pull requests.

Add some basic clusterObj tests

---

mapserver.h

See comments at https://github.com/mapserver/mapserver/pull/5870#issuecomment-531785730
> 
>     Numlabels - or any similar counters - should be immutable. So following that logic numstyles should also be immutable.
>     Leader - no so sure about that one. Looks like styles and labels aren't even exposed to MapScript and users must work through the helper methods. Makes sense since they are arrays.

Make numlabels and labelLeaderObj immutable

---

mapserver.h

Revert "Make numlabels and labelLeaderObj immutable (#5929)" due to line ending changes (thanks Visual Studio). 
This reverts commit 5a06fc84789bc2daf9f936dcaeacad382673f6ce.

Revert #5929 due to line endings

---

mapscript/python/tests/cases/style_test.py
mapserver.h

See mailing list post at [1]. Setting a style symbol name has no effect. This pull request makes it immutable and adds a test for the newer `setSymbolByName` as added in #1835
[1] https://lists.osgeo.org/pipermail/mapserver-users/2019-November/081492.html

Add setSymbolByName test

---

mapscript/phpng/php7module.i

This patch adds a SWIG typemap to return gdBuffer as a string in PHP, similar to the Python Mapscript behaviour (ref. RFC-16).  This fixes the bug reported in #5798, where PHP Mapscript msIO_getStdoutBufferBytes() returns a resource handle instead of the actual buffer.

Add PHP typemap for gdBuffer. 

---

mapscript/mapscript.i
mapscript/phpng/php7module.i

The default exception handling routines in mserror.i is missing if the only mapscript module defined is SWIGPHP7. This causes all mapscript errors to throw an uncathable 'E_ERROR' and quit php instead of throwing an exception.

Include mserror.i and call msSetup() for PHP7 Swig mapscript

---

mapservutil.c

This fixes a segfault issue with mode=legendicon and certain conditions where the opaque pointer back to the parent mapObj is used, for instance when dealing with truetype symbols along a line.

Backport pull request #5926 from master.

---

mappostgis.c

Backport of https://github.com/mapserver/mapserver/pull/5949
Fixes a performance issue dating from 7.0
The wfs_filter_postgis.map wfs_filter_postgis_property_is_equal_case_insensitive
test case exercices this code path.

[Backport 7.4] PostGIS backend: translate insensitive equality comparison as PostgreSQL lower(foo::text) = lower('bar').

---

mapogroutput.c

On Windows the following error is thrown in the debugger as the status variable was never set:
`Run-Time Check Failure #3 - The variable 'status' is being used without being initialized.`
This caused OGR output from a WFS cache to return:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows/1.1" version="2.0.0" xml:lang="en-US" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="NoApplicableCode" locator="mapserv"/>
</ows:ExceptionReport>
```
This pull request initialises the variable at the top of the function (maybe unnecessary?), and also sets when retrieved from the cache using …

Initialize status variable for cached WFS results

---

mapogcsld.c
msautotest/wxs/expected/wms_getstyles_expressions1.xml
msautotest/wxs/expected/wms_getstyles_expressions10.xml
msautotest/wxs/expected/wms_getstyles_expressions11.xml
msautotest/wxs/expected/wms_getstyles_expressions12.xml
msautotest/wxs/expected/wms_getstyles_expressions2.xml
msautotest/wxs/expected/wms_getstyles_expressions3.xml
msautotest/wxs/expected/wms_getstyles_expressions4.xml
msautotest/wxs/expected/wms_getstyles_expressions5.xml
msautotest/wxs/expected/wms_getstyles_expressions6.xml
msautotest/wxs/expected/wms_getstyles_expressions7.xml
msautotest/wxs/expected/wms_getstyles_expressions8.xml
msautotest/wxs/expected/wms_getstyles_expressions9.xml
msautotest/wxs/wms_styles_expressions.map

See issue at #5526. 
This pull request makes checks for operators case-insensitive so "AND", "and", and "Annd" in a Mapfile expression will all produce an SLD filter. 
The functions `strcasecmp`, `strcasestr`, and `toupper` are used to ensure this. 
A new test Mapfile has been added to ensure these filters are created in each case. 
TODO - add test for brackets e.g. `AND(`

Use Case Insensitive Filters for SLD Output

---

appveyor.yml
mapscript/csharp/swig_csharp_extensions.i
mapscript/python/pyextend.i
mapscript/python/pymodule.i
mapscript/python/tests/cases/style_test.py
msautotest/mspython/test_bug_check.py

See issue #5982
- Python test suite now passes when built with SWIG 4.0.1 with this pull request. 
- Appveyor checks Python with both SWIG 3.0.12 (in the x32 build) and SWIG 4.0.1
- C# binding code commented out to successfully build, but I'm unsure if there are any unwanted side-effects
- PHP and Perl are built and tested on Travis so this will need updating to check these are working

Updates to build MapScript with SWIG 4.0.1

---

Makefile
msautotest/pymod/mstestlib.py

Should address remark of https://github.com/mapserver/mapserver/pull/6000#issue-381070490

msautotest: in --strict mode, as run by the CI, make absence of expected file an error

---

appveyor.yml
mapscript/python/README.rst

This pull request automatically uploads Python MapScript Wheels for Windows to https://pypi.org/project/mapscript/ on each new MapServer release. 
A release is defined by a new tag on the master branch e.g. rel-7-4-3, and will be created for each [MapServer Release](https://github.com/mapserver/mapserver/releases)
Currently Appveyor builds for the following Python versions, so each of these will have a Wheel created:
- Python 2.7 x32
- Python 2.7 x64
- Python 3.6 x64
It may be time to also add in a Python 3.7 environment. 
I've tested the process on my branch, with tags on master, and uploading to https://test.pypi.org/manage/project/mapscript/release/7.6.0/
In addition a "source distribution" is created that can be used to automatically generate MapScript API documentation (updates still …

Automated PyPI Wheels for Windows on a new release

---

mapwcs.cpp
mapwcs.h
mapwcs11.cpp
mapwcs20.cpp
mapwfs.cpp
mapwfs11.cpp
mapwms.cpp
msautotest/wxs/expected/wcs_multiple_metadatalink_100_cap.xml
msautotest/wxs/expected/wcs_multiple_metadatalink_110_cap.xml
msautotest/wxs/expected/wcs_multiple_metadatalink_200_cap.xml
msautotest/wxs/expected/wfs_multiple_metadataurl_100_cap.xml
msautotest/wxs/expected/wfs_multiple_metadataurl_110_cap.xml
msautotest/wxs/expected/wfs_multiple_metadataurl_200_cap.xml
msautotest/wxs/expected/wms_multiple_metadataurl_cap.xml
msautotest/wxs/wcs_multiple_metadatalink.map
msautotest/wxs/wfs_multiple_metadataurl.map
msautotest/wxs/wms_multiple_metadataurl.map

Implements https://lists.osgeo.org/pipermail/mapserver-dev/2020-March/016159.html
For WMS, use wms_metadataurl_list as the master that references other metadata
items:
```
wms_metadataurl_list "xml html"
wms_metadataurl_xml_format "text/xml"
wms_metadataurl_xml_type "TC211"
wms_metadataurl_xml_href "http://example.com/testXML"
wms_metadataurl_html_format "text/html"
wms_metadataurl_html_type "TC211"
wms_metadataurl_html_href "http://example.com/testHTML"
```
FOR WFS, this is with wfs_metadataurl_list
For WCS, this is with wcs_metadatalink_list

WMS/WFS/WCS: support multiple metadataurl/metadatalink in GetCapabilities output

---

CMakeLists.txt
mapcontext.c
maplabel.c
mapogroutput.cpp
mapshape.c
mapshape.h
mapstring.cpp
mapxbase.c

There are still uses of ANSI FILE* API, but this should hopefully
fix #5995, but untested
Likely not appropriate for backport

Use GDAL large file API (UTF-8) compatible in a number of places

---

mappostgis.cpp
msautotest/mspython/test_postgis.py

mappostgis: restore case insensitive comparisons for 'using unique' in DATA

---

mappostgis.c
msautotest/mspython/test_postgis.py

Fixes #6060
Backport of https://github.com/mapserver/mapserver/pull/6062

[Backport 7.6] mappostgis: restore case insensitive comparisons for 'using unique' in DATA

---

mapscript/python/mapscript/__init__.py

This pull request removes the submodule name from the class names. 
Currently all classes are imported into the package root namespace in `__init__.py`. 
However the class module names are still set to the subpackage. This change will make them appear in the root, based on the answer at https://stackoverflow.com/questions/1808522/masquerading-real-module-of-a-class/
Before:
```python
>>> import mapscript
>>> mapscript.classObj.__module__
'mapscript.mapscript'
```
After:
```python
>>> mapscript.classObj.__module__
'mapscript'
```
For Python MapScript users nothing will change. The main benefit is for the ongoing autodoc work with Sphinx.

Remove submodule name from mapscript package

---

mapscript/mapscript.i
mapscript/swiginc/class.i
mapserver.h

This pull request builds on https://github.com/mapserver/docs/pull/327 and allows direct links from the planned generated MapScript docs to Mapfile keyword syntax. 
It also adds property docstrings to the classObj in mapserver.h
Initially I added these as Python only docstrings [here](https://github.com/mapserver/mapserver/pull/6071/commits/19d40f2a4572e3eba76e57f1dabc1a9d788114e4), but using the SWIG feature and adding to where classObj is defined allows types to be automatically generated for each property. 
Keeping the docstrings and property declarations together also has more chance of them being maintained.

Add classObj property strings and update MapScript docstrings

---

appveyor.yml

This automates deploying to PyPI for any release tag (previously the PS script had assumed this would be on a master branch, and would have deployed to the test PyPI site). 
Release tags are assumed to be in the format `"rel-7-6-0"` which should exclude any release candidates and betas from being deployed. 
```
("rel-7-6-0" -cSplit "-").Count -eq 4
("rel-7-6-0-rc4" -cSplit "-").Count -eq 5
```

Deploy MapScript to PyPI for any release tag

---

appveyor.yml

Fixes current issue with Appveyor builds and fixes logic on when to deploy Python Wheels to PyPI

Fix deploy build logic and hide Python deprecation warnings

---

mapscript/mapscript.i
mapscript/phpng/CMakeLists.txt
mapscript/phpng/php7module.i

- fixes reports of Debian-GIS not including the required file 'mapscript.php' (https://bugs.launchpad.net/ubuntu/+source/mapserver/+bug/1884854)
- will install the file into the PHP_EXTENSTION_DIR, such as:
`-- Installing: /usr/lib/php/20170718/mapscript.php`

install PHPNG required file 'mapscript.php'

---

appveyor.yml
mapscript/python/CMakeLists.txt
mapscript/python/pymodule.i

This pull request builds and test Python MapScript on Python 3.7
This requires a small fix due to a chnage in the Python C-API:
> The result of PyUnicode_AsUTF8AndSize() and PyUnicode_AsUTF8() is now of type const char * rather of char *. (Contributed by Serhiy Storchaka in bpo-28769.)
https://docs.python.org/3/whatsnew/3.7.html#c-api-changes
In addition, the following changes have been made to the Appveyor build:
* Only two Python versions are fully built - py27-32 and py37-64. There is little reason to do a full MapServer compile for every single version of Python (with py 3.8 out and 3.9 on the way). Other Python versions will only build on a release so that bindings are automatically pushed to PyPI
* pytest is run using the `-m` switch to ensure it is the version used in the virtual …

Add py37 MapScript build and testing

---

mapscript/java/CMakeLists.txt

Currently the Travis build with optimisations has a 15,000 line log file: https://travis-ci.org/github/mapserver/mapserver/jobs/699304461 = lines 15357
Many of these are warnings related to the Java MapScript bindings e.g.:
` /home/travis/build/mapserver/mapserver/build/mapscript/java/edu/umn/gis/mapscript/mapscriptJAVA_wrap.c:12271:19: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
`
This is caused by the optimisation flag:
`make cmakebuild MFLAGS="-j2" CMAKE_C_FLAGS="-O2...`
See https://github.com/mapserver/mapserver/blob/master/ci/travis/script.sh#L30
A similar issue arose at https://github.com/microsoft/LightGBM/issues/1556
See SWIG notes at http://www.swig.org/Doc4.0/Java.html#Java_compiling_dynamic
> Important
> If you are going to …

Hide some SWIG Java warnings

---

mapmssql2008.c

Use CURVEPOLYGON(()) instead of CURVEPOLYGON(CIRCULARSTRING()) when fetching geography data from SQL Server. This will increase the performance.

Don't use CIRCULARSTRING when fetching geography data from SQL Server.

---

mapogr.cpp

We observed that our WFS (MapServer + GeoPackage utilizing the OGR backend) is a lot slower when specific spatial operators are used in a filter condition. Although the spatial index in the GeoPackage could be used to accelerate those specific operators it was not.
By adding a bounding box filter to the request passed down to OGR whenever possible (= depending on which operator is used) the spatial index in GeoPackage is utilized for those requests resulting a very significant performance improvement.

Add a bounding box filter to requests passed down to OGR whenever possible

---

maptemplate.c

- recent browsers throw error of "The character encoding of the HTML document was not declared." when using template=openlayers
- this adds the content encoding type to the meta tag in the OpenLayers template

add content encoding to OL template

---

mapmssql2008.c
mapogr.cpp
maporaclespatial.c
mapows.c
mapows.h
mappostgis.cpp
mapshape.c
msautotest/mssql/expected/wfs_mssql_describefeature.xml
msautotest/mssql/expected/wfs_mssql_describefeature_custom_type.xml
msautotest/mssql/wfs_mssql.map

This pull request allows GML types to be set automatically for the MSSQL driver, but still allow individual fields to be overwritten manually if required. See #5408 and #5418
I believe this was the original intention of the code, but from debugging and testing I don't believe this has ever been the case. 
The code currently checks the "gml" namespace for "type", "width", and "precision" using msOWSLookupMetadata. However, these properties only ever exist with a property name e.g. 
```
gml_[item name]_type
gml_[item name]_precision
gml_[item name]_width
```
Therefore, the searches always return 0, and the auto values are always used. 
It looks like the code has been copied from driver to driver. 
As in the test case included in the pull request:
```
METADATA
"gml_include_items" "all" …
```

Allow custom override for gml_types "auto"

---

mapscript/mapscript.i
mapserver.h

This pull request adds docstrings to the classObj that will be available to the MapScript API docs as part of [RFC 132](https://mapserver.org/development/rfc/ms-rfc-132.html). 
The SWIG ` %feature("docstring"...` approach has been switched to using Doxygen-style strings, which are less intrusive, and better match standard C code comments. 
A few rules are required to ensure these comments are carried to the Sphinx documentation:
- `///<` is used to apply a comment to the preceding code (see [Doxygen docs](https://www.doxygen.nl/manual/docblocks.html#memberdoc))
- the new MapScript API docs will make use of the [Sphinx autosummary module](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) to display class properties. Note this only takes text up to the first period in …

Add property docstrings to classObj

---

mapscript/swiginc/map.i

This make it possible to create a legend for all layers even if they are not within scale range.

Make it possible to send scale_independent to drawLegend via MapScript

---

maperror.c
mapscript/swiginc/class.i
mapserver.h
mapshape.h

A few other minor Doxygen comment fixes included. 
Undocumented struct properties hidden from SWIG for DBFInfo and shapefileObj. 
Relates to https://www.mapserver.org/fr/development/rfc/ms-rfc-132.html

Document the DBFInfo and shapefileObj with Doxygen comments

---

mapmssql2008.c
mapserver.h
mapstring.cpp

There has been an encoding problem in the SQL Server plugin. Queries used SQLExecDirect instead of SQLExecDirectW making the plugin dependent on that the systems locale matched the encoding of the map-file. For Swedish characters on Swedish Windows the map file needed to be in ISO-8859-1 but other connections such as PostGIS reguire the map-file to be in UTF-8. So combining different type of connections was a problem. The plugin was also using a bad pattern when reading attributes from SQL Server, see https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/odbc-driver-behavior-change-when-handling-character-conversions?view=sql-server-ver15

Fixes for using none ascii characters in Sql Server connection strings, queries and results

---

mapproject.c

Patch provided by @rouault.
See discussions from #6155
This ensures MapServer and GDAL are using the same PROJ_LIB variable when set in a Mapfile using: 
`CONFIG "PROJ_LIB" "C:\MapServer\bin\proj\SHARE"`

Apply CONFIG PROJ_LIB to GDAL/OGR PROJ settings

---

fontcache.c

We had a lot of errors like msGetGlyphByIndex(): General error message. unable to load glyph 36d for
font "arial" when using MapServer via MapScript in a multithreaded application. We solved this by adding locks to msGetGlyphIndex() and msGetGlyphByIndex() similar to those used in msGetGlyphOutline().

Add more locking to global font cache

---

mapwmslayer.c

When WMS layers use memory files as temporary storage we can't delete all existing memory files before creating a new. This will generate a lot of "Unable to access file..." errors in a multi-threded application that uses MapScript.
However, we can always remove the temporary memory files even if the layer has debug enabled.

Don't remove all temporary memory files for WMS layers before creating a new

---

.github/workflows/check-crlf.yml

- now also excludes directories (as our msautotest contains a few TAB and PDF files with CRLF)

Enable check-crlf github action

---

scripts/vagrant/packages.sh

This fixes issue #6154 about failure on Vagrant build.

Add Kitware's APT repository to get recent CMake in Vagrant build

---

mapmetadata.c
msautotest/wxs/expected/ows_metadata_layer_raster.xml
msautotest/wxs/expected/ows_metadata_layer_vector.xml
msautotest/wxs/expected/ows_metadata_wms_capabilities111.xml
msautotest/wxs/expected/ows_metadata_wms_capabilities130.xml
msautotest/wxs/ows_metadata.map

Implements #6166 
In addition, removes erroneous default date output.

Metadata: use attribution_title if available (#6166)

---

mapwfs11.cpp

… which is non-conformant with WFS XML schema (fix #6170)

WFS 1.1/2.0: do not write empty ows:WGS84BoundingBox element when layer extent is unknown

---

msautotest/pymod/mstestlib.py

- handle encoding when opening mapfile

[msautotest] update mstestlib for Python3

---

renderers/agg/include/agg_rendering_buffer.h

There is a small typo in renderers/agg/include/agg_rendering_buffer.h.
Should read `rendering` rather than `renrdering`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, renrdering -> rendering

---

msautotest/pytest.ini

For some unknown reason, they are attempted to be accessed when
running 'pytest msautotest' within Vagrant, despite not being
in the white list of ``testpaths``

pytest.ini: explicitly exclude php and myssql sub directories

---

mapserver.h

Documentation of the `labelObj` properties as part of [RFC 135](https://mapserver.org/development/rfc/ms-rfc-132.html)
Items to note relating to the `labelObj` and changes in this pull request:
- `labelLeaderObj *leader;` has been hidden from SWIG - to use correctly it would need to have getters and setters added to the bindings (similar to `expressionObj expression;`)
- the following properties are documented in the current [SWIG docs](https://mapserver.org/mapscript/mapscript.html#labelobj-attributes) but have been removed: autoangle, antialias, backgroundcolor, backgroundshadowcolor, backgroundshadowsizex, backgroundshadowsizey
- there is an unused `MINLENGTH` property that can be set via a Mapfile on a `LABEL` object. It is currently undocumented as was introduced as part of …

Document labelObj properties

---

.travis.yml
appveyor.yml
mapscript/python/README.rst
mapscript/python/mapscript/__init__.py

As per #6101
This adds Windows support for Python MapScript 3.8, and testing under Appveyor. 
Also tests PHP 7.4 and Python 3.8 on Ubuntu with Travis. 
CI build times will increase with this pull request. Python 3.6 is EOL at the end of 2021 so perhaps this could be dropped from the CI?

Add MapScript Python 3.8 Support

---

mapfile.c
maplabel.c
mapserver.h

This pull request documents labelCacheObj and associated objects properties, which can then be used to generate SWIG API docs as part of [RFC 132](https://mapserver.org/development/rfc/ms-rfc-132.html)
Other changes are as follows:
- The current MapScript API docs don't currently reflect changes made to the labelling related objects  since the [RFC98 changes](https://github.com/MapServer/MapServer/issues/4673). There is a 'new' (from 2013) `labelCacheSlotObj` which now has several of the properties previously associated with `labelCacheObj`: cachesize, markercachesize, numlabels, nummarkers. 
- A deprecated property of `labelCacheMemberObj` and related code has been removed as annotation layers were dropped several versions ago. There is mention of the …

Document labelCacheObj and associated objects (RFC 132)

---

mapscript/python/README.rst
mapscript/python/mapscript/__init__.py

This avoids import errors on invalid or empty `MAPSERVER_DLL_PATH` settings.
Also add a Troubleshooting section to the ReadMe that will be displayed at https://pypi.org/project/mapscript/

Filter out any invalid PATHs when loading Python MapScript

---

mapserver.h

This pull request adds comments to the `layerObj` as part of https://mapserver.org/development/rfc/ms-rfc-132.html
Struct variables have been reordered based on SWIG or not SWIG and immutable/mutable. This reduces the many `#ifdef` scattered throughout the declaration (any issues with this please let me know). 
The following have been made immutable as they are custom types that would require getters/setters to be added to work correctly:
```
expressionObj utfdata;
LayerCompositer *compositer;
hashTableObj connectionoptions;
```
If `connectiontype`  is not set using the SWIG function `setConnectionType` the vtable is not initialized properly - however it is left as mutable as it can be used for INLINE layers and there are tests around this. 
Additional changes in the pull request:
- …

Add labelObj and layerObj comments to mapserver.h

---

mapprimitive.h
mapserver.h

Documents the legendObj and lineObj structs to make available for autogenerated SWIG docs as part of https://mapserver.org/development/rfc/ms-rfc-132.html
No hidden surprises or changes, although legendObj has a couple of properties not available to SWIG that can be removed when deprecated).

Document legendObj and lineObj

---

mapscript/python/pyextend.i
mapscript/swiginc/map.i
mapscript/swiginc/mapzoom.i
mapserver.h

Documents the mapObj struct to make available for autogenerated SWIG docs as part of https://mapserver.org/development/rfc/ms-rfc-132.html
Reorders properties to reduce the `#ifdef SWIG` occurrences. 
Also fixes a few of the method docstrings in the .i SWIG files. 
No changes to immutable etc. as part of this pull request, although a few properties should be investigated further:
- `height` and `width` can be set by SWIG. However the Python bindings have custom methods added to set these by the size property: https://github.com/MapServer/MapServer/blob/e0372c34f5bfb3f539d2737fd98c9f68f9de7d2a/mapscript/python/pyextend.i#L276
- `int *layerorder;` can be set via SWIG but I think should be at least immutable and propbably accessed via methods - again this is the case for the Python bindings: …

Update mapObj comments and docstring fixes

---

.travis.yml

- PHP 7.1 was end-of-life in 2018, and ended security fixes at end of 2019
- Python 2.7 ended security releases at end of 2019
Remaining tests are:
- PHP 7.4, 7.3, 7.2
- Python 3.8, 3.7, 3.6

drop PHP 7.1 + Python 2.7 from TravisCI builds

---

mapprimitive.h
mapproject.h
mapserver.h

Documents properties for `outputFormatObj`,`projectionObj`, and the map primitives `rectObj`, `lineObj`, `pointObj` and `shapeObj` as part of https://mapserver.org/development/rfc/ms-rfc-132.html

Document outputFormatObj, projectionObj and map primitives

---

mapserver.h

Document `webObj`, `styleObj` and `referenceMapObj` as part of https://mapserver.org/development/rfc/ms-rfc-132.html
Going through these led to noticing a couple of missing Mapfile keywords in the docs:
- https://github.com/MapServer/MapServer-documentation/issues/463
- https://github.com/MapServer/MapServer-documentation/issues/462
- https://github.com/MapServer/MapServer-documentation/issues/461

Document webObj, styleObj and referenceMapObj

---

maperror.h
mapscript/swiginc/resultcache.i
mapserver.h
mapsymbol.h

Document the following structs as part of https://mapserver.org/development/rfc/ms-rfc-132.html
- scalebarObj
- resultCacheObj
- symbolSetObj
- labelLeaderObj
- errorObj
- symbolObj

Document various MapServer structs

---

mapwfs.cpp

Currently, they are displayed even when the Mapfile has `DEBUG 0`. 
With this update they are displayed for `DEBUG 3` and higher to avoid cluttering logs when reporting errors only.

WFS: Only display cache debug messages for MS_DEBUGLEVEL_V

---

.github/workflows/backport.yml

- go back to our working workflow for backports (as it has been working for 13 months smoothly)
- will continue to monitor m-kuhn/backport and its comparisons to Gaurav0/backport (following both for activity)

revert backport workflow

---

cmake/FindPostgreSQL.cmake

Issue #6239. This changes the IF block for PG_CONFIG.  When pg_config is found, cmake searches only the libraries and include paths output by pg_config.  If pg_config is not found, then it searches the defaults and other listed paths in the find_path and find_library commands.

Issue #6239. If pg_config is found, cmake searches paths specified by pg_config.

---

mapowscommon.h
mapwfs.cpp
mapwfs20.c
msautotest/wxs/expected/wfs_200_exception_getfeaturebyid_invalid_id.xml
msautotest/wxs/expected/wfs_200_exception_getfeaturebyid_nofeature.xml

Pull request to add in the changes from https://github.com/rouault/mapserver/commit/89919a719ea2bb8a477590e0fb4d2e04f65ad2d6 as discussed in #4852
Currently for WFS requests by FID if no feature is found a HTTP 403 error is returned with a `OperationProcessingFailed`.
This pull request chnages it to HTTP 404 and a `NotFound` exception code. 
Also discussed / related to #6268.

WFS GetFeaureById return HTTP 404 when not found and not HTTP 403

---

maplayer.c
mapwms.cpp

Fix for #6258
All works fine in my setup and all tests are passing in CI, but I'd appreciate any reviews prior to merging, in case there are unforeseen implications of the update. 
- It does add a new `#include "mapows.h"` to `maplayer.c`. 
- `gml_wmsfilter_flag` was the best I could come up with for this temporary metadata item. It is added and then removed once the query has run. 
Note the metadata is only updated in the `msWMSApplyFilter` which is only used when filters are run on WMS so other code paths should be unaffected.

Improve WMS Filter performance

---

maplayer.c

When debugging the `GetMetadata` request I noticed `msLayerGetExtent` was called 3 times when generating the layer metadata. If an extent is not set for the layer then (with the MSSQL driver - and probably the other database drivers) a SQL request is made to find the extent of the layer based on the data. 
As noted in the comments for `msLayerGetExtent`:
> ** If layer->extent is set then this value is used, otherwise the
> ** driver-specific implementation is called (this can be expensive).
> **
> ** If layer is not already opened then it is opened and closed (so this
> ** function can be called on both opened or closed layers).
> 
This pull request caches the extent on the layer object on the first call, so all subsequent calls return this value instantly. 
It speeds up the `GetMetadata` …

Cache Calculated Layer Extents

---

scripts/vagrant/packages.sh

Launching a brand new Vagrant VM fails with the following error:
> default: ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/pip/2.7/get-pip.py instead.
We get this because the default version of get-pip.py at https://bootstrap.pypa.io/get-pip.py no longer supports Python 2, so we either have to fetch the version for Python 2.7 (what this PR does), or call get-pip.py with `python3`.  However the latter probably won't work out of the box anyway since the bionic Vagrant VM contains Python 3.4 and the message above says that the new script requires 3.6+.
I defer to those of you who know our Vagrant config better than me to tell me if this PR is the right fix, or if instead we should switch the Vagrant setup to …

Fix Vagrant config to fetch get-pip.py for Python 2.7 since Python 2 support was dropped in pip 21.0

---

maphttp.c
mapserv.c
mapserv.h
mapservutil.c

Potential solution for IIS/FastCGI where we push some high-value environment variables into the CPL environment (using CPLSetConfigOption) and then reference them there (CPLGetConfigOption). This is against **branch-7-6** rather than main since the config file work would replace this.
Should be ok for non-IIS/FastCGI as well.
--Steve

WIP: Use CPLSetConfigOption/CPLGetConfigOption for some CGI/FastCGI-related env vars.

---

mapscript/java/examples/DrawMap.java
mapscript/python/examples/wxs.py
mapscript/python/pyextend.i
mapscript/python/tests/cases/clone_test.py
mapscript/python/tests/cases/image_test.py
mapscript/python/tests/cases/layer_test.py
mapscript/python/tests/cases/map_test.py
mapscript/python/tests/cases/style_test.py
mapscript/python/tests/cases/symbolset_test.py
mapscript/python/tests/runtests.py
mapscript/swiginc/class.i
mapscript/swiginc/layer.i
mapscript/swiginc/map.i

This pull request removes various deprecated and legacy functions from the SWIG MapScript API. 
MapScript API docs (currently in development) will reflect these changes and are generated from the code as part of [RFC 133](https://mapserver.org/development/rfc/ms-rfc-132.html). 
Changes for 8.0 release / migration guide:
- `getMetaData` function removed from `mapObj`, `classObj`, and `layerObj` - metadata can now be accessed as a `hashObj` property on all these classes, and then modified using `hashObj` methods.
Example:
```python
map = mapscript.mapObj(map_file)
map.setMetaData("ows_onlineresource", "http://dummy.org/")
```
Should be rewritten:
```python
map = mapscript.mapObj(map_file)
map.web.metadata.set("ows_onlineresource", "http://dummy.org/")
```
- `setProcessing` removed from the …

Mapscript legacy functions cleanup

---

mapfile.c
mapscript/php/style.c
mapserver.h

Looks like this was added in along with other SYMBOL properties, but is not required. Replaced by `OFFSET`?

Remove unused and undocumented style->position

---

mapwfs.cpp
msautotest/wxs/expected/wfs_200_exception_getfeature_resourceid_filter_invalid_typename.xml

Sets the locator to "resourceid" and exception code to InvalidParameterValue when requested featureid is inconsistent with feature in TYPENAMES. 
From the CITE WFS2.0 test description: 
>If a feature instance identified by the RESOURCEID parameter is not of the type specified by the TYPENAMES parameter, the server shall raise an InvalidParameterValue exception where the "locator" attribute value shall be set to "RESOURCEID".
http://opengeospatial.github.io/ets-wfs20/apidocs/org/opengis/cite/iso19142/basic/filter/ResourceIdFilterTests.html#inconsistentFeatureIdentifierAndType-javax.xml.namespace.QName-

Set locator and exception code so CITE WFS2 test will pass

---

mapcopy.c
mapfile.c
mapogcsld.c
mapogr.cpp
maprendering.c
mapscript/php/style.c
mapserver.h
maptemplate.c
maputil.c
xmlmapfile/mapfile.xsl

Removes [STYLE>BACKGROUNDCOLOR](https://mapserver.org/mapfile/style.html#mapfile-style-backgroundcolor) as part of [RFC 133](https://mapserver.org/development/rfc/ms-rfc-133.html)
Remaining usage of `BACKGROUNDCOLOR` was in the autogeneration of styles from OGR in `mapogr.cpp`. This required reworking the function to produce 2 style objects, and keep the current ordering logic for `PenBrush` styles. msautotests all passing with same results as previously.

Remove BACKGROUNDCOLOR from STYLE object

---

cgiutil.c
mapows.c
mapscript/python/tests/cases/ows_test.py
mapscript/swiginc/owsrequest.i

The following adds in POST request functionality from within MapScript via a new `loadParamsFromPost` method. Related to #6344.
Note - this will allow POST data to be passed as a string via MapScript, but does not support reading from a buffer. 
The only change to existing CGI functionality is allowing `request->contenttype` to be set directly on a request object rather than always reading from the CGI environment. 
Associated Python test added to the test suite, which can also serve as an example.

Allow POST requests from MapsScript

---

.travis.yml

- most communities have moved to irc.libera.chat
- recently Freenode servers & channels were reset. Future there is unknown.

update IRC channel for build notifications

---

mappostgis.c

(follow-up of fixes #6181, fixes #6230) (fixes https://github.com/MapServer/MapServer/pull/6347#issuecomment-870002856)
Backport of PR #6354

[Backport 7.6] PostGIS: fix ST_Intersects() with bounding box that is a point 

---

mapogr.cpp

(Like described in pull request [#6356](https://github.com/MapServer/MapServer/pull/6356), but now the code is also updated to include Spatialite.)
Hi, we are running a multitute of MapServer+GPKG stacks and we recently upgraded our MapServers to 7.6.3 (+ cherrypicked [#6325](https://github.com/MapServer/MapServer/issues/6325)). With this new stack we noticed significant performance degradation, request that took +/-300ms now took up to 3.3sec with SQLite datasources.
After some investigation we looked at the SQL that is being generated for the GeoPackage & Spatialite and noticed that the query used with JOIN on the rtree tables incombination with the Intersects() and the ORDER BY causes the long running queries. Removing one of those 3 makes the queries run "fast" again but with of couse …

spatialindex for sqlite sources in filter

---

appveyor.yml
msautotest/mssql/create_mssql_db.bat
msautotest/mssql/expected/line.json
msautotest/mssql/expected/multiline.json
msautotest/mssql/expected/multipoint.json
msautotest/mssql/expected/multipolygon.json
msautotest/mssql/expected/multipolygon_with_hole.json
msautotest/mssql/expected/null_line.json
msautotest/mssql/expected/null_multiline.json
msautotest/mssql/expected/null_multipoint.json
msautotest/mssql/expected/null_multipolygon.json
msautotest/mssql/expected/null_point.json
msautotest/mssql/expected/null_polygon.json
msautotest/mssql/expected/point.json
msautotest/mssql/expected/polygon.json
msautotest/mssql/expected/polygon_with_hole.json
msautotest/mssql/expected/wfs_mssql_maxfeatures.json
msautotest/mssql/expected/wfs_mssql_maxfeatures_order.json
msautotest/mssql/expected/wfs_mssql_maxfeatures_qs.json
msautotest/mssql/include/bdry_counpy2_mssql.map
msautotest/mssql/include/mssql_connection.map
msautotest/pymod/mstestlib.py

Updates the Appveyor Windows CI to use Visual Studio 2019, and the new MSVC 2019 release-1928-x64-dev buildkit from https://www.gisinternals.com/sdk.php
- update to MSSQL 2019
- updated to use PROJ7
- test JSON results now all updated to include `"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::3857" } },` - likey due to updates to the GDAL dependencies in the buildkit
One strange issue is that for JSON responses, there is now an additional `\r` in the break between the header output and the rest of the JSON response body. This broke the Python code to DEMIME a response in `mapserver\msautotest\pymod\mstestlib.py`
A fix was added to the Python code to get this working again, but an upstream fix would be better.

Update Appveyor builds to Visual Studio 2019

---

mapscript/python/CMakeLists.txt

Trying to package/build mapserver head before 8.0, it failed for me during install/fake, as it tried writing to the system dirs in usr/local while CMAKE_INSTALL_PREFIX and DESTDIR were properly defined - and ignored.
i think this was an oversight in the large commit done in dd310d211. Not 100% confident about all cases, but this fixes the 'install to alternate dir' problem for me. Cmake expert feedback welcome :)

Fix python module installation with alternative root/prefix

---

mappostgis.c

Fixes https://github.com/MapServer/MapServer/pull/6355#issuecomment-877290417
Backport of https://github.com/MapServer/MapServer/pull/6369

[Backport 7.6] PostGIS: fix ST_Intersects() with collections with PostGIS < 2.5

---

mapserver.h

These `ref` links are used when generating the MapScript API documentation. 
Highlighted by the `nitpick` Sphinx option - see https://github.com/MapServer/MapServer-documentation/pull/582

Fix broken mapfile doc references

---

mapmvt.c

The number associated with the MOVETO command should be the number of
coordinate *pairs*. We wrote twice that number. This caused for
example the OGR MVT driver to reject such geometries.

MVT generation: fix writing of point/multipoint geometries

---

SECURITY.md

- according to the mapserver-dev thread (https://lists.osgeo.org/pipermail/mapserver-dev/2021-July/016572.html) and the recent discussion in the PSC meeting on 2021-08-26 (https://github.com/MapServer/MapServer/wiki/PSC-Meeting-2021-08-26)
- this was the suggestion by Daniel, Even, Jeff (all with the same idea, yet different wording).
- the wording that seems to be the most clear was provided by Daniel, and is used in this pull request

update SECURITY.md for supported versions

---

mapscript/python/README.rst

Add another cause of the dreaded `ImportError: DLL load failed: The specified procedure could not be found.` error to the Python MapScript Readme.

Add note on GEOS and Python MapScript

---

mapogr.cpp

We observed that our WFS (MapServer + GeoPackage utilizing the OGR backend) is a lot slower when the DWithin spatial operator is used in a filter condition. Although the spatial index in the GeoPackage could be used to accelerate this specific operator it was not.
This PR adds a bounding box to the request passed down to OGR when the DWithin spatial operator is used. For the bounding box we use the envelope of the geometry with the distance used as the buffer. Below is an example of the filter:
`<fes:Filter>
<fes:DWithin><fes:ValueReference>begrenzingPerceel</fes:ValueReference>
<gml:Point gml:id="geo.1" srsName="EPSG:28992"><gml:pos dimension="2">257050.19722083333 470137.85737916664</gml:pos></gml:Point><fes:Distance units="m">12.287004477416515</fes:Distance></fes:DWithin> …

Define rect for a dwithin filter condition

---

mapogr.cpp
msautotest/wxs/expected/wfs_ogr_gpkg_filter_intersects_point.xml
msautotest/wxs/wfs_ogr_gpkg.map

When `wfs_use_default_extent_for_getfeature` is set to `off` on a layer, the geometry in an intersect filter is used to calculate the `rect`. This `rect` is the input for the `BuildMbr` spatialite function. When the geometry in the intersect filter is a POINT, the POLYGON resulting from `BuildMbr` is invalid, because all vertices in the POLYGON are the same. This POLYGON is used in the `Intersect` spatialite function. It seems to depend on the version of spatialite whether or not this is an issue. Some versions of spatialite seem to handle an intersect with an invalid POLYGON fine and some never result in a match. This PR tries to make this more robust and checks if the `rect` is a POINT and in this case uses a POINT as the input for the intersect, in all other cases the `BuildMbr` is …

Invalid geometry from buildmbr when a point is used a base for the rect

---

.github/workflows/start.sh
ci/travis/before_install.sh

The previous fix `ENV CRYPTOGRAPHY_DONT_BUILD_RUST=1` only works up to 3.4 so pin the version to avoid `error: can't find Rust compiler` (e.g. [here](https://app.travis-ci.com/github/MapServer/MapServer/jobs/541345228#L1801)
See https://stackoverflow.com/questions/66118337/how-to-get-rid-of-cryptography-build-error and also https://github.com/pyca/cryptography/issues/5771

Pin cryptography version

---

cmake/FindOracle.cmake

Added nnz21 libnnz21 to the ORACLE_NNZ_NAMES list.

FindOracle.cmake: add support for OCI 21

---

mapwfslayer.c

Added version WFS 1.1.0 supported by MapServer as a client (in the error message).

msBuildWFSLayerGetURL: added WFS 1.1.0 in error message

---

msautotest/gdal/wmsclient.map
msautotest/gdal/wmsclient_3543.map
msautotest/renderers/wmsclient.map

- cleaner url, and this endpoint is the one that is constantly monitored for uptime

[msautotest] correct WMS endpoint

---

mapogr.cpp

Fixes leak introduced recently in master per 736baa6d55634efa027baffb08401ce38ef92caa
Fixes following failures with the Travis ASAN job:
FAILED run_test.py::test[wfs_filter_ogr_wfs_filter_dwithin_xml] - AssertionEr...
FAILED run_test.py::test[wfs_filter_ogr_wfs_filter_dwithin_units_xml] - Asser...
FAILED run_test.py::test[wfs_ogr_native_sql_wfs_ogr_native_sql_32_xml] - Asse...

OGR layers: fix memory leak with DWithin filter

---

appveyor.yml

Recent builds have been failing on Appveyor as even though the `Python_ROOT_DIR` hint is specified for Python 2.7, Python 3.10 is being found by CMake (e.g. [here](https://ci.appveyor.com/project/MapServer/mapserver/builds/41884531/job/h529h23wjw1abl9n#L210)). 
The simple workaround is to rename the Python 3.10 directory (it looks like some change may be required in MapScript to get Python working with 3.10 as some tests are failing). 
I'm not sure what the correct fix here is. There is discussion on user set variables being ignored by CMake at https://gitlab.kitware.com/cmake/cmake/-/issues/19492#note_597909
As Python2 and Python3 are being built [find_package (Python..](https://github.com/MapServer/MapServer/blob/main/mapscript/python/CMakeLists.txt#L4) is used rather than `find_package …

Fix Appveyor builds by ignoring Python 3.10

---

ci/travis/before_install.sh
ci/travis/script.sh

Attempt to fix errors e.g. at https://app.travis-ci.com/github/MapServer/MapServer/jobs/552166460#L1598
`ERROR: Could not find a version that satisfies the requirement cryptography==3.4.6`
This is turning out to be more complicated than hoped. 
Details so far:
- it looks like something has changed with `pyenv` on Travis. There were no commits to code between the last time Travis passed and when it first start failing (8th of Devember 2021) - see https://app.travis-ci.com/github/MapServer/MapServer/builds
- the issue is that calling `pyenv global $PYTHON_VERSION` in `before_install.sh` no longer seems to point `python` and `pip` to the desired Python version. `.travis.yml` sets `$PYTHON_VERSION` to 3.6, 3.7 and then 3.8. 
- python and pip then fall back to using the system Python which is …

Reconfigure pyenv to fix broken Travis builds

---

mapgml.c
mapogr.cpp
msautotest/wxs/data/withnullvalues.csv
msautotest/wxs/data/withnullvalues.csvt
msautotest/wxs/expected/wfsogr10_datetime.xml
msautotest/wxs/expected/wfsogr10_nullnumeric.csv
msautotest/wxs/expected/wfsogr10_nullnumeric.xml
msautotest/wxs/wfs_ogr.map

We encountered incorrect date/time values in WFS GetFeature responses of our (GeoPackage backed) MapServer instances. Only the year was rendered correctly. All other parts where zeroed out. 
While investigating the issue it was discovered that the code that handles date/time values (`msParseTime` in `maptime.c`, called by `msGMLWriteItem` in `mapgml.c`) expects the provided date/time strings to be formatted in ISO 8601. Unfortunately the OGR backend (`mapogr.cpp`) provides date/time strings in a different format (yyyy/mm/dd hh:mm:ss) and `msParseTime` only succeeds in parsing the year part of the date/time string and silently ignores the rest. Resulting in malformed GML output.
It was discovered that the `msOGRGetValues` function treats every field as a string field, leaving it up to OGR …

Properly handle datetime fields

---

README.rst

- adds badge for the persistent (or 'concept') DOI, so we won't have to change the link for each release

add DOI badge to README

---

shptreevis.c

Use correct size to avoid the following:
` warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data`

Fix compilation warning in shptreevis

---

mapfile.c

See #6468 - allow `STLYE ANGLE` to be between -360 and 360 to allow clockwise and anti-clockwise values (supported by current codebase).

Allow negative angles for STYLE

---

msautotest/renderers/symbolrot_negative.map

This msautotest file is identical to [symbolrot.map](https://github.com/MapServer/MapServer/blob/main/msautotest/renderers/symbolrot.map) but uses negative values. The images produced look identical (need to confirm there are no floating point issues that may require a new reference image). 
This seems to confirm that a `STYLE ANGLE` can use negative values as discussed in #6463. 
Tests will currently fail at the moment with the error `loadStyle(): General error message. Invalid ANGLE, must be between 0 and 360 (line 77) <br>`
@sdlime - should the validation for `STYLE ANGLE` allow the range -360 to 360 as with the other angles? Or is further testing required?

Add negative ANGLE tests

---

scripts/vagrant/packages.sh

Updates `vagrant up` to install Python3 and configure `python` and `pip` to default to Python 3.6

Update Vagrant to use Python3

---

mapproject.c

- since the PROJ 6.0.0 release, PROJ is more strict and rejects invalid coordinates (see https://github.com/OSGeo/PROJ/blob/master/src/fwd.cpp#L56 )
- since the PROJ 8.0.0 release, PROJ changed the default log level to be `PJ_LOG_ERROR` (from `PJ_LOG_NONE`) (see https://github.com/OSGeo/PROJ/blob/master/src/ctx.cpp#L90 )
- I'm one of the unlucky ones it seems, because all (yes all) of my mapfiles cause hundreds or thousands of PROJ error messages filling up my MapServer log, for each map draw
- imagine your MapServer log is something like:
```
PROJ: Error: utm: Invalid latitude
PROJ: Error: utm: Invalid latitude
PROJ: Error: utm: Invalid latitude
PROJ: Error: utm: Invalid latitude
PROJ: Error: utm: Invalid latitude
PROJ: Error: utm: Invalid latitude
PROJ: Error: utm: Invalid latitude …
```

handle PROJ6 invalid coordinates error in MapServer log

---

mapfile.c
mapserver.h

During the [2022 Joint OGC – OSGeo – ASF Code Sprint](https://github.com/opengeospatial/developer-events/wiki/2022-Joint-OGC-%E2%80%93-OSGeo-%E2%80%93-ASF-Code-Sprint), we tried to use the current main branch of the MapSever repo from the ZOO-Kernel to publish results as OGC API - Features.
By doing so, we realized that it may be useful to get access to a `msSaveConfig` function that is prototyped here from the MapServer C-API. This function would simply permit to save the config file.
From our understanding, with the current main branch, when you publish a new OGC API - Features you should have a new item in the `maps` `hashTable` to get the URL `http://SERVER/MYMAP/ogcapi/` to work properly. 
The function currently provided does not take into account saving the plugins, it should be …

Add the msSaveConfig function to the MapServer C-API

---

etc/mapserver-sample.conf

- add to mapserver-sample.conf :
- MS_MAP_BAD_PATTERN
- default PROJ_LIB value

add MS_MAP_BAD_PATTERN to sample conf

---

mapscript/python/pyextend.i
mapscript/swiginc/map.i

This update fixes issues when building MapScript for Python 3,10 with (as yet unreleased) SWIG 4.1.0. 
- Calls to `PyObject_CallMethod` (used by MapScript for writing images) need to use `Py_ssize_t` rather than `int` for specifying size (to allow output > 2GB). See https://bugs.python.org/issue40943
- SWIG methods all now have `__SWIG` appended to them which broke `intarray___setitem__(order, i, self->layerorder[i]);` - I'm unsure why the method name rather than array access was used in the first place.

Python MapScript updates to work with Python 3.10

---

mapraster.c
mapuvraster.c

There are a few instances of `if(layer->debug == MS_TRUE)` statements. Layers that use the following syntax don't get these debug statements:
```
LAYER
DEBUG 5 # any value apart from 1/ON/TRUE are ignored by the above statements
```    
Also includes a couple of updates changing the hardcoded 5 to use `MS_DEBUGLEVEL_VVV` as used throughout the rest of the codebase.

Ensure all layer debug statements are output

---

msautotest/php/colorObjTest.php
msautotest/php/hashtableObjTest.php
msautotest/php/symbolObjTest.php

Clean Valgrind run with that.
They are mostly related to $map object being local to the setUp() function if not using $this->map syntax. And the issue is that if it is destroyed, then depending objects will point to freed memory.
Caveats: I don't know anything about PHP...

msautotest/php: fix use-after-free issues (fixes #6537)

---

mapproject.c
mapproject.h
mapscript/mapscript.i
mapscript/swiginc/line.i
mapscript/swiginc/point.i
mapscript/swiginc/rect.i
mapscript/swiginc/reprojection.i
mapscript/swiginc/shape.i
msautotest/php/maps/reprojection.map
msautotest/php/reprojectionObjTest.php

Legacy MapScript projection operations are very slow when used in batch context - e.g. looping over a series of geometries and reprojecting. This pull request exposes the reprojectionObj to MapScript and adds overloaded project methods to point, line, rect and shape classes. Use looks like so (in Perl):
```
my $proj_26915 = new mapscript::projectionObj('epsg:26915');
my $proj_4326 = new mapscript::projectionObj('epsg:4326');
my $reprojector =  new mapscript::reprojectionObj( $proj_26915,  $proj_4329 );
while (my $shape = $layer->nextShape()) {
my $point = $shape->getCentroid();
$point->project($reprojector);
}
```
--Steve

Expose reprojectionObj to MapScript

---

CMakeLists.txt

#6518 adds the utility but doesn't actually install it.

Also install coshp utility.

---

map2img.c
mapobject.c
mapproject.c
mapproject.h
mapserv-config.cpp
mapservutil.c
maputil.c

PROJ 9.1 recognizes the PROJ_DATA environment variable, as a replacement
for PROJ_LIB (both are still recognized by PROJ >= 9.1. PROJ_LIB will be
retired in PROJ 10, whose release is unplanned for now)
Cf https://github.com/OSGeo/PROJ/pull/3253

Apply special processings of PROJ_LIB to PROJ_DATA as well

---

mapscript/python/CMakeLists.txt
mapscript/python/requirements-dev.txt

CI is failing due to linting issues, as a Python line is 130 characters:
https://ci.appveyor.com/project/MapServer/mapserver/builds/44357880/job/wuf5k2b7gvn2e5y2#L421
Seems as though there must have been a change in Flake8 (a new version was released yesterday). 
Pull request includes a specific version of Flake8 to ensure this doesn't happen again.

Increase Python max line length for linting

---

share/ogcapi/templates/html-bootstrap4/collection-items.html
share/ogcapi/templates/html-plain/collection-items.html

in case you have a layer/data entry with zero features (extent incompatible with map extent, sql query that returns 0 records, broken FILTER expression in mapfile...) right now accessing it via OGCAPI using the html format yields
```
{"code":"ConfigError","description":"Template rendering error. [inja.exception.render_error] (at 52:22) variable 'response.features.0.properties' not found (collection-items.html)."}
```
PR makes sure that there are features before trying to enumerate properties, fixing this error - the default HTML template is properly rendered with an empty map zoomed to the world, and properly reports `Number of returned items: 0`
@sdlime ? does this make sense to you ?

[ogcapi] make sure there are features before accessing them in jinja templates

---

mapquery.c

fixes #6580 - after all we're looping on all map layers so we cant just `goto restore_old_filter`, so i just copy/pasted a similar idiom found in other places in mapquery.c
more eyes welcome on the logic, but fixes the double-free for me in the case where the layer extent doesn't overlap with the map/query extent.

reset layer filteritem to its old value when the query extent doesnt overlap the layer extent

---

mapwms.cpp

See discussions at https://lists.osgeo.org/pipermail/mapserver-dev/2022-August/016847.html
> It appears that as of 8.0 a layer must have a NAME. In the past it has been
possible for a layer not to have a NAME if it had a  GROUP.
> with a WMS request. Apache throws a 500 error "End of script
output before headers". I define a LAYER with a GROUP but no NAME
This update  ensures the same behaviour as 7.6 and avoids crashing the server.

Check if a LAYER has a NAME before accessing the property

---

mapogcapi.cpp

Possible fix for #6613. 
The database drivers use `lp->startindex` for generating queries with `rownnum` for paging. E.g.
https://github.com/MapServer/MapServer/blob/6c3486b3577d7efc6988d4e319df45807419d59f/mapmssql2008.c#L1577
This doesn't appear to be set when using the OGC Features API, only `map->query.startindex` is set. 
Paging in WFS works by setting `lpQueried->startindex`. 
https://github.com/MapServer/MapServer/blob/e789297546c00d60f6aad3fb51e53cc4b2dd8e35/mapwfs.cpp#L2961
Testing locally with MSSQL this correctly sets the `rownum` based on the offset. I'm unsure of any possible side effects of this change though. 
An `offset=20` produces a SQL query with `[rownum] >= 21 and [rownum] < 31` - is this the correct? Or should the `1+ offset` be changed to simply `offset`?

Set layer startindex for paging in OGC Features API

---

mapdebug.c
maperror.c
maperror.h
mappostgis.c

Fixes https://github.com/MapServer/MapServer-private/issues/2
Backport of https://github.com/MapServer/MapServer/pull/6616#issuecomment-1252356026

[Backport 7.6] Redact password= content in msError() and msDebug() messages

---

.github/workflows/cifuzz.yml

CI-Fuzz triggers fast OSS-Fuzz checks on pull requests. See https://google.github.io/oss-fuzz/getting-started/continuous-integration/ for more details

Add a github action CI-Fuzz workflow

---

mapfile.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52066

loadProjection(): avoid write heap-bufer-overflow on invalid PROJECTION block

---

mapfile.c
mapscript/python/pyextend.i
mapscript/swiginc/map.i
mapserver.h

Update to address #6626. 
[Python ](https://github.com/MapServer/MapServer/blob/545b44a4924505c97d2192b042091cc38972fc5f/mapscript/python/pyextend.i#L24)and C# MapScript both allow loading a Mapfile from a string. 
MapServer 8.0 now uses a `CONFIG` file that allows setting keys for plugins and other settings.  This update allows a config file to be used when loading the Mapfile from a sting:
`mapscript.fromstring("MAP NAME TEST END", r"C:/MapfileResources/", config_file)` 
I've not tested if the C# approach works - the following is reported in the SWIG output, although I'm unsure if this is relevant:
```
[  6%] Swig compile ../mapscript.i for csharp
/home/runner/work/mapserver/mapserver/mapscript/v8/../swiginc/map.i:62: Warning 516: Overloaded method mapObj::mapObj(char *,int,configObj *) …
```

Allow a CONFIG to be used when loading a Mapfile from a string

---

mapfile.c

Found locally with ossfuzz
```
Direct leak of 1304 byte(s) in 1 object(s) allocated from:
#0 0x54de9e in __interceptor_calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:77:3
#1 0x5c6ce8 in msGrowClassStyles /src/MapServer/mapfile.c:3020:48
#2 0x5c8513 in loadClass /src/MapServer/mapfile.c:3262:12
#3 0x5d0f1e in loadLayer /src/MapServer/mapfile.c:3968:12
#4 0x5ec0a0 in loadMapInternal /src/MapServer/mapfile.c:6053:12
#5 0x5ef850 in msLoadMap /src/MapServer/mapfile.c:6333:6
#6 0x58b1df in LLVMFuzzerTestOneInput /src/MapServer/build/../fuzzers/mapfuzzer.c:50:13
#7 0x45cb33 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
#8 0x45c31a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned …
```

Fix memory leak related to styles on invalid mapfile

---

mapfile.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52102

msLoadMap(): fix double-free related to labels

---

mapfile.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52111

loadHashTable(): fix memory leak in error code path

---

mapshape.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52130

mapshape.c: avoid 'undefined-shift' issue with SWAP_FOUR_BYTES() macro

---

mapfile.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52114

msLoadMap(): fix memleak in error code path related to symbol loading

---

maplabel.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52123

msLoadFontSet(): fix memleak in error code path

---

maplabel.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52131

msLoadFontSet(): fix null pointer dereference

---

mapfile.c

As far as I can see, this was broken in the nominal case since https://github.com/MapServer/MapServer/commit/f595e91f1b418db72b806162dba4470109ac8dc1
So this feature is not used in msautotest, nor documented (https://mapserver.org/search.html?q=LATLON doesn't return anything relevant)
Probably that the mapObj::latlon member would be better initialized by taking the geographic CRS of the mapObj::projection.

msLoadMap(): fix nullptr dereference when using LATLON keyword

---

maplexer.c
maplexer.l

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52175

maplexer.l: avoid non-null terminated msyystring_buffer that can cause read heap-buffer-overflow

---

maplexer.c
maplexer.l

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52175

[Backport 7.6] maplexer.l: avoid non-null terminated msyystring_buffer that can cause read heap-buffer-overflow

---

mapshape.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52209

msSHPReadShape(): avoid integer overflow

---

mapshape.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52213

msSHPOpenVirtualFile(): fix integer overflow

---

mapogr.cpp

Likely fix for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52223 (couldn't reproduce the leak with the reproducer and current main, but this commit does fix a leak)

msOGRShapeFromWKT(): fix memleak in error code path

---

mapproject.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52259

msIsAxisInverted(): avoid undefined-shift on invalid code

---

mapsymbol.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52272

loadSymbol(): fix potential memory leak

---

mapxbase.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52283

msDBFOpenVirtualFile(): avoid integer overflow

---

maplexer.c
maplexer.l

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52305
Backport of https://github.com/MapServer/MapServer/pull/6712

[Backport 7.6] maplexer.l: fix heap-buffer-overflow issues with NUL characters

---

mapfile.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52371

loadColor(): fix memory leak if LABEL.COLOR is repeated

---

mapfile.c

This was introduced per 6da3b29110

writeLayer(): fix wrong argument that cause invalid stack reading (perhaps fixes #6628)

---

mapowscommon.c

xmlSchemaCleanupTypes() is deprecated since libxml 2.10, and will be removed in a future version (as a public callable function)
This function is called by xmlCleanupParser() since https://github.com/GNOME/libxml2/commit/36e5cd5064d3477a0500f6183d68b18b7493568a#diff-65f1a082f56ebd52b4eaabdbe54d6e516736c8d9186b8c82c8ca55ad3cac105eR12119 14 years ago, so no need to call it explicitly.
Fixes #6614

Remove call to deprecated xmlSchemaCleanupTypes()

---

mapfile.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52947

freeLabelLeader(): fix memleak (including in nominal code path)

---

appveyor.yml

When searching for Python versions 3.10 and 3.11 are picked up instead of 2.7 on Appveyor. Quick fix for now is to ignore these two Python versions until they are supported by MapScript and/or 2.7 is deprecated.

Ignore Python 3.11 on Appveyor

---

mapbits.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53339

Bit manipulation: avoid undefined-shift behavior when left-shifting of 31 bits

---

mapcontext.c
mapgdal.cpp
mapogroutput.cpp
mapwcs11.cpp
mapwcs20.cpp
mapwmslayer.c

In GDAL 3.7dev, VSILFILE* is no longer an alias for FILE* (see https://github.com/OSGeo/gdal/pull/6883), so we have to adjust our usage to be correct.
This MapServer change is backward compatible with GDAL < 3.7 too
CC @szekerest

Fix usage of FILE* and VSILFILE*

---

mapscript/swiginc/shapefile.i
mapscript/tcl/mapscript_wrap.html

I believe the docs incorrectly reference `MS_SHP` vs `MS_SHAPEFILE` in two locations.  Certainly, `MS_SHP_POINT` is not defined in `mapshape.h`

doc: correct MS_SHP to MS_SHAPEFILE

---

mapwfs.cpp

Similar to #6131 and #6131 - this change avoids selecting fields from a database which aren't required. 
As discussed in the comments at https://github.com/MapServer/MapServer/pull/6131#issuecomment-675750118
> any fields referenced in a CLASS are selected at the database level even if never used for a WFS request (this was also the case in > my previous pull request) - I presume there is no way to get round this due to buildLayerItemList
Simply setting the number of classes to 0 prior to retrieving features from the database avoids adding in all fields referenced in CLASSes in a LAYER. For example if a layer has a CLASS similar to below then `Myfield` is added to the database `SELECT` query (in [buildLayerItemList](https://github.com/MapServer/MapServer/blob/8d6c9ecdd29c75b3976788a0d28786 …

Optimise WFS requests by reducing fields selected

---

.travis.yml
ci/travis/before_install.sh
msautotest/php/reprojectionObjTest.php

- this means tests will include PHP 7.4, 8.1, 8.2 (8.0 tests are dropped)
- even though PHP 7.4 is EOL, it is still the default for Ubuntu Focal, the host testing environment (so leaving 7.4 tests in, for now)

upgrade TravisCI to test PHP 8.2.x mapscript

---

maperror.c

This pull request adds the version numbers of PROJ and GDAL to the version output for MapServer (using `mapserv -v` on the command line, and also present in some error messages). Both are required dependencies (at least since 8.0) so will always have a value. 
As different versions of PROJ and GDAL can have an impact on how MapServer behaves, and what is supported, it is useful to be able to easily access this information, and allow users to report it when having problems. 
The output will now look similar to the following:
```
MapServer version 8.1-dev PROJ version 7.2 GDAL version 3.4 OUTPUT=PNG 
OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE
SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=SVGCAIRO SUPPORTS=ICONV 
SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER …
```

Add Proj and GDAL versions to MapServer version output

---

mapfile.c
mapservutil.c

This does a couple of things discovered through various upgrade work (by myself and others):
1. Allows map.size and map_size CGI parameters as aliases for mapsize. Older versions of OpenLayers (OL) supported a OpenLayers.Layer.MapServer layer type that used an alias instead of just mapsize. This should allow using MapServer 8 without having to re-work an old OL interface.
2. Allows runtime substitution on the web TEMPLATE property.
--Steve

Small changes missed in the initial 8.0 release.

---

maperror.c
mapmssql2008.c

Pull request to address #6772. Similar to #6616. 
Currently the following text is sent to any client application if a MS SQL database connection fails:
```
msMSSQL2008LayerOpen(): Query error. Couldnt make connection to MS SQL Server 2008 with connect string 'SERVER=(local)\SQL2019;DATABASE=msautotest;uid=sa;pwd=Password12!;'.
<br>
Error reported was '[Microsoft][ODBC SQL Server Driver][DBMSLPCN]SQL Server does not exist or access denied.'.
<br>
This error occured when trying to make a connection to the specified SQL server.
<br>
Most commonly this is caused by <br>
(1) incorrect connection string <br>
(2) you didn't specify a 'user id=...' in your connection string <br>
(3) SQL server isnt running <br>
(4) TCPIP not enabled for SQL Client or server <br>
```
This update logs connection …

Update MS SQL Server connection error logging

---

mapogroutput.cpp

Intro
------
A [Seek-Optimized (SOZip)](https://sozip.org) is a [ZIP](https://en.wikipedia.org/wiki/ZIP_(file_format)) file that contains one or several [Deflate](https://www.ietf.org/rfc/rfc1951.txt)-compressed files that are organized and annotated such that a SOZip-aware reader can perform very fast random access (seek) within a compressed file.
SOZip makes it possible to access large compressed files directly from a .zip file without prior decompression. It is not a new file format, but a profile of the existing ZIP format, done in a fully backward compatible way. ZIP readers that are non-SOZip aware can read a SOZip-enabled file normally and ignore the extended features that support efficient seek capability.
For more details, consult the …

ZIP OGR output: use CPLAddFileInZip() to be able to generate SOZip-enabled files

---

maplayer.c

Similar to #6785 but for WMS requests. 
If a WMS request includes specific STYLES e.g. `&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&STYLES=MyStyle&TILED=false&LAYERS=MyLayer&` then MapServer sets the `CLASSGROUP` of the `LAYER` to the selected style. In this example `MyStyle`. 
The generic `buildLayerItemList` currently goes through all classes in a layer to find any references to fields (anything in [SquareBrackets]) and adds them to the SELECT clause sent to the datasource. 
This update checks if `CLASSGROUP` has been set, and if it has then ignores any `CLASS` that doesn't have a matching `GROUP` name. Fields in these unused classes aren't required and not selecting them can improve performance. This is most noticeable in layers which have many classes …

Optimise WMS requests by ignoring any fields that won't be used

---

maporaclespatial.c

When using wfs paging mapserver create a wrong query, for example for query:
```
DATA "GEOM FROM (
select * from my_table
) USING SRID 21781 NONE"
```
mapserver create wrong query
```
SELECT "ID", rownum, GEOM FROM (
select * from my_table
)SELECT * from (SELECT atmp.*, ROWNUM rnum from (SELECT "ID", rownum, GEOM FROM (
select * from my_table
) order by rowid) atmp where ROWNUM<=2) where rnum >=1
```
basically concatenate the "normal" query with paging query. The correct query should be
```
SELECT * from (SELECT atmp.*, ROWNUM rnum from (SELECT "ID", rownum, GEOM FROM (
select * from my_table
) order by rowid) atmp where ROWNUM<=2) where rnum >=1
```

Fix wfs paging on oracle

---

mapagg.cpp
mapdraw.c
maperror.c
mapfile.c
mapquery.c
mapserver.h
mapservutil.c
mapsymbol.c

These will contribute increased stability and security. Specifically:
- https://github.com/MapServer/MapServer/pull/6584  
- https://github.com/MapServer/MapServer/pull/6577
- https://github.com/MapServer/MapServer/pull/6458
- https://github.com/MapServer/MapServer/pull/6466 
Plus fixing (cherrypick) a memory leak discovered while writing OGCAPI tests. 
--Steve

Collection of backports from the 8.0 development work.

---

CMakeLists.txt
mapmetadata.c
msautotest/mssql/expected/cluster_mssql_getmetadata.xml
msautotest/wxs/expected/ows_metadata_empty_layer_param.xml
msautotest/wxs/expected/ows_metadata_invalid_layer_param.xml
msautotest/wxs/expected/ows_metadata_layer_raster.xml
msautotest/wxs/expected/ows_metadata_layer_vector.xml
msautotest/wxs/expected/ows_metadata_missing_layer_param.xml

As part of updating Appveyor to the new GDAL/PROJ SDK one of the MS SQL Server tests was failing relating to a `GetMetadata` request:
> mapserv -nh "QUERY_STRING=map=C:/projects/mapserver/msautotest/mssql/cluster_mssql.map&REQUEST=GetMetadata&LAYER=cities"
Caused the following: `msIO_vfprintf(): General error message. Possible buffer overrun.`
Note on Windows (or at least Appveyor and a local machine) `HAVE_VSNPRINTF` is false. 
Only similar issue is #2599 - the string to write is larger than the buffer. Looking at other functions that write XML I tried the approach used for WFS 2.0 which fixed the issue. 
https://github.com/MapServer/MapServer/blob/68fd623eddc772137952509a8008209a02cd1e85/mapwfs20.c#L729-L736
Note this also updates the output to use UTF-8 (which is probably what we want …

Fix GetMetadata possible buffer overrun

---

mapfile.c

The BINDVALS, UTFDATA and UTFITEM attributes in layers were missing from writeLayer()
COLORRANGE and DATARANGE were only written in STYLEs if RANGEITEM was also defined, but kernel density layers also make use of those attributes without using RANGEITEM

Improve round-trip of mapfiles through mapscript

---

appveyor.yml

Python 2.7 is out-of-life for more than 3 years now...

appveyor.yml: remove support for testing python 2.7 builds

---

mapfile.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57056

loadLayer(): fix memory leak in case of error in loadLayerCompositer()

---

mapfile.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57261
The manual cleanup that was done was incomplete (it should have called freeCompositingFilter()), and it is actually useless as the caller loadLayer() takes care of cleaning.

loadLayerCompositer(): fix memleak in error code paths

---

mapcopy.c
mapfile.c
mapscript/swiginc/class.i
mapscript/swiginc/layer.i
mapscript/swiginc/map.i
mapscript/swiginc/shape.i
mapscript/swiginc/style.i

- tested with MS4W and PHP 8.1 on Windows
- (it helped by examining the initial commit for this at https://github.com/MapServer/MapServer/pull/5883/ )
- the layer is now written out as:
```
CONNECTIONOPTIONS
"xxx"	"xxx"
END # CONNECTIONOPTIONS
```

fix write of CONNECTIONOPTIONS (fixes #6852)

---

maplexer.c
maplexer.l

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57788

mapfile parser: fix double-free when included file doesn't exist

---

maplexer.c
maplexer.l
mapsymbol.c

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52125

maplexer: avoid call to exit(1) when read error in parser file

---

mapshape.c

The lintian QA tool reported a spelling error for the Debian package build:
* suported -> supported

Fix spelling errors.

---

CMakeLists.txt

The '/w' option is specific to MSVC in Windows. So, check the compiler
type before adding that compiler flag. This fixes the following error
in mingw toolchain.
cc: error: no such file or directory: '/w'

CMake: Check compiler type for MSVC speicific option

---

CMakeLists.txt

Defining STDC_HEADERS macro includes stdlib.h in regex.c which is
required for free, abort etc. function declarations. This fixes the
following compiler error with mingw clang.
regex.c:2042:3: error: call to undeclared library function 'free' with type
'void (void *)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
regex.c:2784:11: error: call to undeclared library function 'abort' with type
'void (void) __attribute__((noreturn))'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

cmake: Define STDC_HEADERS for regex in mingw toolchain

---

maprendering.c

The wrong routine name is reported in `msDrawLineSymbol`.

Fix routine name in msDrawLineSymbol error message

---

appveyor.yml

This pull request:
- Updates to new Python versions for testing. 3.7 will only be tested on tagged releases in Appveyor. It is EOL next month: https://endoflife.date/python
- Re-enables the "reprojection rect and datum shift" test. This was disabled due to failing previously (see #6824 and #6827), but now appears to be working again

Update Appveyor Python versions

---

mapscript/python/CMakeLists.txt

An oversight on my part - the MapScript comments were not added to the Python module. This pull request fixes that, and I'll make an update to the docs shortly to correct this for the 8.0.1 release.

Output doxygen comments in Python MapScript module

---

mapfile.c
mapscript/python/tests/cases/label_test.py
mapscript/swiginc/label.i

This pull request allows the new functionality in #6884 of using an expression in a LABEL PRIORITY in MapScript. 
It takes a similar approach to setting attribute bindings for properties, which requires using the appropriate attribute constant such as `MS_LABEL_BINDING_PRIORITY`:
```python
label = mapscript.labelObj()
label .setExpressionBinding(mapscript.MS_LABEL_BINDING_PRIORITY, "[MY_ATTRIBUTE] * 2")
```
This is a little clunky but is at least consistent with setting attribute bindings:
```python
label = mapscript.labelObj()
label.setBinding(mapscript.MS_LABEL_BINDING_COLOR, "NEW_BINDING")
```
While testing this I noticed that the `writeLabel` function used to write Mapfile objects ignored expressions. This seems an oversight also for the `LABEL` `SIZE` expression. If this approach …

Allow Expressions to be set for LABEL properties using MapScript

---

mapservutil.c
msautotest/api/expected/ogcapi_missing_api_signature1.txt

Follow-up to #6862 - where a missing slash was causing tests to fail in #6919. 
This allows Mapfile keys to be used in a URL path, with or without a trailing slash:
```
http://example.com/mykey/?request=WMS...
http://example.com/mykey?request=WMS...
```
An OGCAPI test is also updated as part of this pull request as it is now valid to use a URL without an additional `ogcapi` in the path. 
I'm unsure why this test is currently passing in main but not when the repo structure was changed. @jmckenna - could you merge this and test with a rebase on #6919?

Allow Mapfile key to be only element in PATH_INFO

---

src/mapogr.cpp

The functions in the OGR_ST_ C API use int, not GBool. The later is typedef to int, so there is no issue per se, but better use the type of the API to avoid issues
(note: GBool is likely going to be deprecated soon in GDAL. Cf https://github.com/OSGeo/gdal/issues/8288 At least within the GDAL code base: it will likely remain available to external code for a bit)

mapogr.cpp: replace use of GBool by int

---

src/mapscript/python/CMakeLists.txt
src/mapscript/python/requirements-dev.txt

Python linting and formatting is added to pre-commits in #6937 so no need to run as part of builds.
Also update requirements-dev.txt to remove flake8 and use newer versions of wheel and setuptools now Python 2.7 support is dropped.

Remove Flake8 from Python builds

---

msautotest/wxs/expected/wms_getstyles_expressions13.xml
msautotest/wxs/expected/wms_getstyles_expressions14.xml
msautotest/wxs/expected/wms_getstyles_expressions15.xml
msautotest/wxs/expected/wms_getstyles_expressions16.xml
msautotest/wxs/expected/wms_getstyles_expressions17.xml
msautotest/wxs/wms_styles_expressions.map
src/mapogcsld.c

Fix for #6911. This update generates SLD for a class using [list expressions](https://www.mapserver.org/mapfile/expressions.html#list-expressions):
```
CLASSITEM "FID"
CLASS
EXPRESSION {2,4,6}
STYLE
COLOR 220 0 0
WIDTH 1
END
```
Will include the following SLD with a request such as `map=mymap&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetStyles&layers=MyLayer`
```xml
<ogc:Filter>
<ogc:Or>
<ogc:PropertyIsEqualTo>
<ogc:PropertyName>FID</ogc:PropertyName>
<ogc:Literal>2</ogc:Literal>
</ogc:PropertyIsEqualTo>
<ogc:PropertyIsEqualTo>
<ogc:PropertyName>FID</ogc:PropertyName>
<ogc:Literal>4</ogc:Literal>
</ogc:PropertyIsEqualTo>
<ogc:PropertyIsEqualTo>
<ogc:PropertyName>FID</ogc:PropertyName>
<ogc:Literal>6</ogc:Literal>
</ogc:PropertyIsEqualTo>
</ogc:Or>
</ogc:Filter>
```
Note when a a list expression …

 Include list expressions in GetStyles SLD output

---

.github/workflows/coverity-scan.yml
ci/travis/before_install.sh

Port of GDAL similar changes of https://github.com/OSGeo/gdal/pull/8571. Credits to @lnicola

CI: workaround add-apt-repository ppa:ubuntugis/ubuntugis-unstable failures

---

src/maptemplate.c

If the Map projection is a geographic coordinate system all geographic CRS template substitutions eg. [maplat] and [maplon] will be skipped. This reintroduces them with reprojection only occurring if the map projection is a projected coordinate system

Fix broken logic for geographic CRS template substitutions

---

msautotest/wxs/expected/wfsogr20_geojson_resulttype_hits.xml
msautotest/wxs/wfs_ogr_geojson.map
src/mapwfs.cpp

Fix for #6403. This prevents a segmentation fault at: https://github.com/MapServer/MapServer/blob/6412a9287a2cb9e07e47f6570aaa8f4e701127bc/src/mapogroutput.cpp#L1043 as the results in the cache is NULL.
The fix removes/ignores any `outputformat=XXX` and so always returns the result count as XML. I'm unsure if the WFS spec defines what should happen in other format cases, but always returning XML at least prevents a server crash.

Avoid segmentation fault when outputformat is defined for resultType=hits

---

fuzzers/CMakeLists.txt
fuzzers/README.md
fuzzers/build.sh
fuzzers/configfuzzer.c

This pull request adds a new fuzzer to the project for the MapServer CONFIG file.
It uses the same approach as the existing mapfuzzer for Mapfiles. 
As discussed at the [OSGeo Codesprint](https://wiki.osgeo.org/wiki/OSGeo_Community_Sprint_2023) a future aim is to get a fuzzer running for a MapServer QUERYSTRING. This however requires a more complicated approach, and setting up of a config file and Mapfile to work with the fuzzer. This pull request was useful to go through the full process before attempting a more complex fuzzer (with thanks to @rouault for the run through and guidance). 
I've built and left this running locally for over 4 hours without any issues being raised by the fuzzer, but I'll attempt to fix any issues raised when run on the full Google infrastructure.

Add a CONFIG file fuzzer

---

msautotest/wxs/expected/wfs_client_100.xml
msautotest/wxs/wfs_client_100.map
src/maphttp.c
src/maphttp.h

While setting up a layer using the [WFS Client](https://www.mapserver.org/ogc/wfs_client.html) I noticed there were no tests in place. 
I've added one (that cascades a WFS service) that works fine locally but fails in the CI. Failing logs as follows:
```
+[Thu Jun 15 13:04:38 2023].66359 HTTP: Before download loop
+[Thu Jun 15 13:04:38 2023].433103 msHTTPWriteFct(id=0, 2496 bytes)
+[Thu Jun 15 13:04:38 2023].433165 HTTP: After download loop
+[Thu Jun 15 13:04:38 2023].433176 msHTTPExecuteRequests() timing summary per layer (connect_time + time_to_first_packet + download_time = total_time in seconds)
+[Thu Jun 15 13:04:38 2023].433242 Layer 0: 0.082 + 0.285 + 0.082 = 0.449s
+[Thu Jun 15 13:04:38 2023].435265 msOGRFileOpen(/tmp/648b0c66_a1b5_5.tmp.gml)...
+[Thu Jun 15 13:04:38 2023].435303 …
```

Add WFS Client Test

---

msautotest/wxs/expected/wms_getstyles_expressions21.xml
msautotest/wxs/expected/wms_getstyles_expressions22.xml
msautotest/wxs/expected/wms_getstyles_expressions23.xml
msautotest/wxs/wms_styles_expressions.map
src/mapogcsld.cpp

A case that was missed in #6983 - multipart expressions such as the following:
`EXPRESSION ( ( [FID] > 1 ) AND ( [FID] <= 10 ) )`
Were still retaining spaces:
```xml
<ogc:And><ogc:PropertyIsGreaterThan><ogc:PropertyName>FID</ogc:PropertyName><ogc:Literal>1 </ogc:Literal>
</ogc:PropertyIsGreaterThan><ogc:PropertyIsLessThanOrEqualTo><ogc:PropertyName>FID</ogc:PropertyName>
<ogc:Literal>10 </ogc:Literal></ogc:PropertyIsLessThanOrEqualTo></ogc:And>
```
This change removes the spaces. A test also added to ensure that strings with spaces e.g. "my value " retain the trailing space.

Remove spaces in SLD exports for multipart expressions

---

msautotest/wxs/expected/wms_getstyles1.xml
msautotest/wxs/wms_styles.map
src/mapogcsld.cpp

The following `STYLE`
```
STYLE
COLOR 255 0 0
WIDTH 2
PATTERN 10 10 END
END
```
Produces SLD output with trailing whitespace:
```xml
<se:SvgParameter name="stroke-dasharray">10.00 10.00 </se:SvgParameter>
```
When working with GeoStyler this style fails to render in OpenLayers. As I understand it this whitespace in nodes are part of the node value so the fix should be on the MapServer side. 
This change ensures the trailing space is trimmed. A new test mapfile has been created for tests for more advanced SLD output from styles.

Remove trailing spaces from stroke-dasharray SLD output

---

src/mapscript/swiginc/layer.i

Since #6268 the queryBy* functions always return MS_SUCCESS if the query was successfully performed, regardless of whether any shapes were found.
Unfortunately the documentation of the Mapscript layerObj has until now not been updated to reflect this change.

bugfix: Correct description of return value for SWIG layerObj->queryByXXX() methods

---

.github/workflows/build.yml
ci/build.sh

Follow-up to #6993 to fix coveralls.io updates, noted by @rouault in https://github.com/MapServer/MapServer/pull/6993#issuecomment-1867815481
There was an issue with quoting around the security token. I've also updated the service name which defaults to `travis-ci` in cpp-coveralls - https://github.com/eddyxu/cpp-coveralls/blob/47f638727512126bc16b1365560854a86db70e7e/cpp_coveralls/__init__.py#L79
The upload now will only happen when merging,and on the main branch rather than ignoring errors. 
Tested in my fork with a token and coveralls.io setup, and working fine: https://coveralls.io/github/geographika/mapserver

coveralls.io fixes

---

.github/workflows/build.yml
ci/build.sh

From https://github.com/MapServer/MapServer/pull/6996#issuecomment-1868267998
> Note that coveralls also work with pull requests (the resulting builds are presented in a separate way in coveralls.io). Which is very useful to check if a new feature/bug fix has sufficient test coverages.
> I'm not totally sure if this is possible with the way we use coveralls, but this is definitely handled by using the github action coverallsapp/github-action@v2 which doesn't require the coveralls secret but uses the regular github secret available in pull requests
This should make it easier to control when to upload - it should now be triggered on any github event, but it should be easy to modify the logic to filter certain events with the `UPLOAD_COVERALLS` variable.

Upload to coveralls.io on pull requests

---

src/mapscript/ruby/rbmodule.i

At least Ruby 3.2 anf SWIG 4.1 expect an integer here, resulting in an int-conversion error with current/upcoming compilers.  Return 0 instead of NULL works with pointer return types, too, should there be a supported Ruby version which uses a pointer in this context.
Related to:
* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

Ruby bindings: Return 0 on exceptions, not NULL

---

src/maporaclespatial.c

This PR fixes a query issue on Oracle databases.
An expression such as `'[FIELD]' =* 'value'` was translated into a SQL expression such as `REGEXP_LIKE( FIELD, '^value$'`, which lacks the closing parenthesis.
The fix has been verified and already used on a production server.

fixed `=*` operator translation for Oracle database

---

msautotest/wxs/expected/wms_raster_query.html
msautotest/wxs/expected/wms_raster_query.json
msautotest/wxs/templates/raster_query.html
msautotest/wxs/wms_raster_query.map
src/maptemplate.c

As discussed in #7014 this adds a new `ignoremissing` property to template items. Example usage:
```
[item name="value_99" nullformat="missing" ignoremissing="true"]
```
If the field `value_99` is missing from the features then the `nullformat` value will be displayed (in this case "missing").
This allows the same template to be used for different datasets which may have slightly different fields, without throwing an error. 
Docs to be updated at https://mapserver.org/mapfile/template.html#format if merged.

Add a ignoremissing option to template items

---

src/mapscript/python/tests/cases/image_test.py
src/mapscript/swiginc/image.i

Follow-up and replacement to #6932 (thanks to @jbfrd) . Additional tests added to the Python test suite. The MapScript API docs should update automatically based on the docstrings on the next release of MapServer / MapScript. 
The test paste function produces the following output (unlike msautotests there is no image comparison as part of the tests - the test just checks the function runs correctly):

Add pasteImage and saveWebImage to Mapscript imageObj

---

src/maperror.c

For native flatgeobuf support a new error code was added but no name / description text to the `ms_errorCodes` array.
To reproduce it would be enough to trigger any `msSetError` which uses `MS_FGBERR` but I think the change is clear enough by itself. In all cases I saw this error the string "(null)" was printed instead because printf was involved at some point and the memory after the last array entry was always null. (and I produced a lot of those error messages while reproducing #7040)

flatgeobuf: add missing error name for MS_FGBERR

---

CMakeLists.txt

As reported in [Debian Bug #1067651](https://bugs.debian.org/1067651) MapServer failed to build on Ubuntu noble with glibc 2.39.
`strlcpy` and `strlcat` were introduced in glibc 2.38 but require `-D_DEFAULT_SOURCE` to actually work after being detected by `check_function_exists()`.

Add -D_DEFAULT_SOURCE for strlcat/strlcpy provided by glibc >= 2.38.

---

msautotest/misc/expected/map2img-argparse-c.txt
msautotest/misc/expected/map2img-argparse-d.txt
msautotest/misc/expected/map2img-argparse-e.txt
msautotest/misc/expected/map2img-argparse-layer_debug.txt
msautotest/misc/expected/map2img-argparse-o.txt
msautotest/misc/expected/map2img-argparse-s.txt
msautotest/misc/map2img-argparse.map
msautotest/pymod/mstestlib.py
src/apps/map2img.c

The map2img command is too optimistic when parsing commandline arguments. In many cases it simply access the option argument without checking if it was actually provided leading sometimes to segfaults for incomplete commandlines.
Note that my change not only improves error handling for options which had non so far but also slightly changes behaviour for some other options.
The `-e` has already a check and custom error message. That message changes a bit with my commit.
Also other options (e.g. all the debug options) had a check before but simply skipped the option if the argument was missing. E.g. `map2img -m file.map -all_debug` would silently ignore the debug argument due to the missing level value before but report an error with my change.

map2img: improve error handling for missing option arguments

---

CMakeLists.txt
ci/build.sh
cmake/FindGDAL.cmake
src/mapscript/csharp/run_test.sh

- FindGDAL.cmake: replace use of deprecated exec_program() by execute_process() (avoid warning with CMake 3.28 or later)
- CMakeLists.txt: raise maximum version in cmake_minimum_required() to 3.29 now that CI tests it
- ci/build.sh: turn CMake warnings as errors
- src/mapscript/csharp/run_test.sh: make sure to run with LC_ALL=C

CMake and CI adjustments

---

.github/workflows/build-mapscript-python.yml
appveyor.yml
src/mapscript/python/CMakeLists.txt
src/mapscript/python/README.rst
src/mapscript/python/pymodule.i
src/mapscript/python/requirements-dev.txt
src/mapscript/python/setup.py.in
src/mapscript/swiginc/layer.i

Updates to Python MapScript in preparation for the 8.2 release.
- Update CI to build all current supported Python versions (3.8 to 3.12) - see https://devguide.python.org/versions/
- Update SWIG to 4.2.1 for Windows Appveyor builds: https://www.swig.org/Release/CHANGES.current
- Update docs to remove references to Python 2.7
- Switch to `build` to create wheels. Current approach was generating warnings - `SetuptoolsDeprecationWarning: setup.py install is deprecated.`
- Add missing doc strings to shadow functions so they appear in the docs
- README updates, and minor code format changes

Python MapScript updates for 8.2 Release

---

src/mapscript/python/CMakeLists.txt

The Debian package build for 8.2.0~beta1 failed to build because the Python MapScript files are not installed in `DESTDIR` as expected.
pip fails to install the Python MapScript files:
```
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "RelWithDebInfo"
ERROR: You must give at least one requirement to install (see "pip help install")
```
This is fixed by specifying the current directory as the working directory is already set to the output directory.

Fix Python MapScript installation.

---

.github/workflows/build-mapscript-php.yml
ci/build.sh
msautotest/php/run_test.sh

- also handles PHPUnit requirements for PHP versions
- the test matrix is now PHP 8.3 (currently `8.3.9`) and PHP 8.2 (currently `8.2.1`)
- this removes the unsupported PHP 8.1 from the test matrix

add PHP 8.3 to test matrix

---

appveyor.yml
msautotest/mspython/test_rq.py

See discussions in #7103. Tests were failing as the GDAL GIF driver wasn't available by default in the Windows SDK.
Failing tests now re-enabled and passing.

Set GDAL_DRIVER_PATH on Windows for the GIF driver

---

src/mapscript/python/CMakeLists.txt

The assumptions about where MapScript should be build don't always hold true for every build system. This allows us to explicitly override it via CMake argument to be whatever is necessary.

allow explicit override of MapScript output folder via CMake variable

---

src/mapproject.c

`+epsgaxis` is [added with a plus here](https://github.com/MapServer/MapServer/blob/main/src/mapfile.c#L1366) and that was not stripped
follow up on #7121
fixes #6973

fix proj epsgaxis= stripping to also work for +epsgaxis=

---

src/apps/map2img.c
src/mapdrawgdal.c
src/mapfile.c
src/mapio.c
src/mapobject.c
src/mapproject.c
src/maprasterquery.c
src/mapscript/swiginc/error.i
src/mapscript/swiginc/layer.i
src/mapserv-config.cpp
src/mapwcs11.cpp
src/mapwfs.cpp

and a change in a MapScript function:
MapScript: layerObj.executeWFSGetFeature(): do not take an extra layerObj* argument, but just use self

Fix compiler warnings with gcc 14.2

---

LICENSE.md

This PR proposes to change the links to the links of `FlatGeobuf` & `FlatBuffers`.
Please review.

fix links to licenses of FlatGeobuf & FlatBuffers

---

src/mapproject.c

Should improve performance issues of https://github.com/MapServer/MapServer/pull/7089

msProjectionContextGetFromPool(): set thread_id to current thread

---

src/mapowscommon.c

CI builds are currently failing with the following:
```
/home/runner/work/mapserver/mapserver/src/mapowscommon.c: In function 'msOWSSchemaValidation':
/home/runner/work/mapserver/mapserver/src/mapowscommon.c:872:5: error: 'xmlMemoryDump' is deprecated [-Werror=deprecated-declarations]
872 |     xmlMemoryDump();
|     ^~~~~~~~~~~~~
In file included from /usr/include/libxml2/libxml/tree.h:28,
from /usr/include/libxml2/libxml/parser.h:16,
from /usr/include/libxml2/libxml/tree.h:17,
from /home/runner/work/mapserver/mapserver/src/mapows.h:43,
from /home/runner/work/mapserver/mapserver/src/mapowscommon.c:35:
/usr/include/libxml2/libxml/xmlmemory.h:161:9: note: declared here
161 |         xmlMemoryDump   (void);
|         ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
It looks like …

Remove call to libxml2 xmlMemoryDump

---

.flake8
.github/workflows/code_checks.yml
.pre-commit-config.yaml

On pull request branches, the `pre-commit/action@v3.0.1` is failing. For example [here](https://github.com/geographika/mapserver/actions/runs/11366259720/job/31616233100#step:4:1).
It looks like `actions/setup-python@v5` requires a Python version to be set as it reports the following warnings:
```
Warning: Neither 'python-version' nor 'python-version-file' inputs were supplied. Attempting to find '.python-version' file.
Warning: .python-version doesn't exist.
Warning: The `python-version` input is not set.  The version of Python currently in `PATH` will be used.
```
Errors are then reported in the pre-commit action:
```
Run python -m pip install pre-commit
python -m pip install pre-commit
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
RUST_BACKTRACE: 1
CARGO_TERM_COLOR: …
```

Pin Python version for precommit action and update flake8

---

.github/workflows/start.sh

Fixes #7179. Also switched to `check-jsonschema` due to deprecation warning:
```
DeprecationWarning: The jsonschema CLI is deprecated and will be removed in a future version. Please use check-jsonschema instead, which can be installed from https://pypi.org/project/check-jsonschema/
```

Update to check-jsonschema and fix URL

---

msautotest/wxs/expected/wms_getstyles_expressions24.xml
msautotest/wxs/expected/wms_getstyles_expressions25.xml
msautotest/wxs/wms_styles_expressions.map
src/mapogcsld.cpp

When using WMS GetStyles requests to generate SLD I noticed some filters were missing. On debugging it became apparent that any string containing a logical operator was failing to generate a filter:
```
EXPRESSION ("[Property1]" = "Not Applicable")
```
Was missing the expected filter:
```xml
<ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>Property1</ogc:PropertyName><ogc:Literal>Not Applicable</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter>
```
`msSLDNumberOfLogicalOperators` had a simple search for `AND`, `NOT`, and `OR` that was finding these words in strings causing errors. This fix attempts to tokenize the string, leaving quoted strings intact to avoid this. It is by no means perfect, and I also had to change previous test cases to have spaces around keywords e.g. `(([FID] > …

SLD Filters missing due to logicial keywords in expressions

---

src/interpolation.c
src/mapcontour.c

GDAL 3.10 has deprecated the usage of the MEM::: open syntax
The workaround without this fix is to use:
MAP
CONFIG "GDAL_MEM_ENABLE_OPEN" "YES"
[ ... layer definitions ... ]
END

Make interpolation and countour compatible of GDAL 3.10

---

src/mapuvraster.cpp

mapuvraster is very leaky in 7.6.x and beyond. 7.4.x series is fine.

mapuvraster: fix hDS file descriptor leak in msUVRASTERLayerGetExtent

---

src/mapproject.c
src/mapproject.h

Helps marginally on the belows scenario of
https://github.com/MapServer/MapServer/issues/7189 where the execution time goes from ~440 ms to ~400 ms
```c++
#include "mapserver.h"
#include <stdio.h>
#include <string>
int main() {
projectionObj src;
msInitProjection(&src);
msLoadProjectionStringEPSG(&src, "EPSG:25833");
const int epsg_list[] = { 25832,
3034,
3035,
3044,
3045,
31468,
31469,
3857,
4258,
4326,
4647,
5650,
5652,
5674,
5675,
5677,
5678,
5679,
4937,
7409,
7423,
9422,
4979 };
double minx=200000;
double miny=5.886e+06;
double maxx=465000;
double maxy=6.075e+06;
for( int epsg: epsg_list )
{
projectionObj dst;
msInitProjection(&dst);
msProjectionInheritContextFrom(&dst, &src);
msLoadProjectionStringEPSG(&dst, (std::string("EPSG:") + std::to_string(epsg)).c_str());
rectObj ext; …
```

msProjectRect(): cache whether source projection is polar when repeatdly projecting from it

---

.github/workflows/build-mapscript-python.yml
appveyor.yml
src/mapscript/python/README.rst

As of 2024-10-07 Python 3.8 is no longer supported. The new 3.13 Python was released on 2024-10-07. 
This pull request removes 3.8 and adds 3.13. The cache folder for SWIG was also updated to match the version in use. 
See https://www.python.org/downloads/ for details. 
Other changes:
- Image updated to Visual Studio 2022
- SWIG updated to 4.3
- SDK updated to https://www.gisinternals.com/query.html?content=filelist&file=release-1930-x64-dev.zip
There is a sqlite3.dll incompatibility between Python 3.13 (version `3.45.3`) and the SDK (version `3.47.1`). The CI copies the DLL into the Python installation. Options to resolve this long-term are in the discussions below.

Update Windows CI and Python Versions

---

msautotest/wxs/expected/wcs10_caps_section_error.txt
msautotest/wxs/wcs_simple.map
src/mapwcs.cpp

WCS 1.0: do not emit twice HTTP headers in case of error on SECTION parameter of GetCapabilities

---

CMakeLists.txt
msautotest/wxs/expected/wms_invalid_request_with_400_status.txt
msautotest/wxs/expected/wms_invalid_request_with_500_status.txt
msautotest/wxs/expected/wms_invalid_request_without_500_status.txt
msautotest/wxs/wms_simple.map
src/maperror.c
src/maperror.h
src/mapfile.c
src/mapservutil.c
src/mapwms.cpp

Currently when one issues an HTTP request that ends up in error, MapServer doesn't emit a HTTP Status header response. Hence the webserver will default to generate a 200 OK one.
This is an historical behavior used by other WMS server implementations (GeoServer, Degree) due to the WMS specification being unclear on what do do. Given that WMS is in a retirement phase, it would be risky to change that behavior by default.
That said there are WMS clients that would enjoy having a proper HTTP 400 or 500 status code. Hence if the MS_WMS_ERROR_STATUS_CODE environment variable / config option is set to ON (typically in the ENV section of the mapserver configuration file), MapServer will emit those status codes.
This relies on code to call the msSetErrorWithStatus() new function. A pass has been …

Add HTTP status code for WMS requests, if MS_WMS_ERROR_STATUS_CODE config option/env variable are set to ON

---

src/maplayer.c
src/mapogr.cpp
src/mappostgis.cpp
src/mapserver.h

Following on from #7197 - another performance improvement related to the PostGIS driver.
The PostGIS driver currently adds a WHERE clause to the SQL to get a single feature from the database, but converts both the field and value to strings - `WHERE "id"::text = '5'`. This means no index is used to find the feature. Thanks to @jandic for finding this issue. 
This pull request avoids casting the field to a string, which in our use case reduced query times from 2730ms to 144 ms - 19 times faster (the table has ~2 million records). 
OGC Feature API queries such as `mymap/ogcapi/collections/MyLayer/items/1?f=json` are affected as are any `MS_STRING` filter expression used for a PostGIS layer. 
Note a similar issue was fixed in `mapogr.cpp` with …

Avoid casting unique ID to string if the field is numeric in PostGIS Driver

---

msautotest/wxs/expected/wms_cap.xml
msautotest/wxs/expected/wms_cap130.xml
msautotest/wxs/expected/wms_cap_latestversion.xml
msautotest/wxs/expected/wms_caps_updatesequence.xml
msautotest/wxs/expected/wms_getfeatureinfo130_empty.txt
msautotest/wxs/wms_simple.map
src/mapwms.cpp

WMS GetFeatureInfo: fix handling of WEB.EMPTY that has been broken in 8.0

---

msautotest/wxs/expected/wms_custom_projection_not_specified.xml
src/mapproject.c

Fixes #7202
```
$ PROJ_DATA=invalid mapserv -conf ../etc/mapserv.conf QUERY_STRING="map=wms_layer_groups.map&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities"
Content-Type: text/html
<HTML>
<HEAD><TITLE>MapServer Message</TITLE></HEAD>
<BODY BGCOLOR="#FFFFFF">
msProcessProjection(): Projection library error. PROJ error &quot;Cannot find proj.db&quot; when instantiating &quot;init=epsg:4326&quot;
```

Emit explicit error message when proj.db cannot be found

---

src/mapserver.h

Fixes build failure on 8.4.0-beta2 on Ubuntu 20.04:
```
In file included from /home/even/mapserver/mapserver-8.4.0-beta2/src/mapoutput.c:31:
/home/even/mapserver/mapserver-8.4.0-beta2/src/mapserver.h:3164:15: error: unknown type name ‘bool’
3164 | MS_DLL_EXPORT bool msLayerPropertyIsCharacter(layerObj *layer,
```

Add stdbool.h inclusion in mapserver.h

---

msautotest/misc/expected/browse.html
msautotest/misc/expected/wms.html
msautotest/misc/expected/wms_projected.html
msautotest/misc/openlayers.map
src/maptemplate.c
src/mapwms.cpp
tests/mapserver-sample.conf

The current built-in [OpenLayers Viewer](http://localhost/mapserver_docs/cgi/openlayers.html) uses [OpenLayers 2](https://openlayers.org/two/) - last updated in 2014. This pull request updates the templates used by the inbuilt viewer to use OpenLayers 10.4 - the current latest version. 
To enable this update a new OpenLayers source was added to the OpenLayers project, to enable map layers to be created using the MapServer CGI parameters, as well as the standard WMS interface. See https://github.com/openlayers/openlayers/pull/16591 for details, and the online example (using the Itasca demo) at https://openlayers.org/en/latest/examples/mapserver-cgi.html. Thanks to @ahocevar for the JS code reviews and accepting the pull request. 
A cut-down version of the OL library has been built - see …

Update the MapServer OpenLayers Viewer to use OpenLayers 10.4

---

.github/workflows/start.sh
appveyor.yml
msautotest/requirements.txt
scripts/vagrant/packages.sh
src/mapscript/python/CMakeLists.txt
src/mapscript/python/requirements-dev.txt
src/mapscript/python/tests/cases/thread_test.py

A few minor changes to Python requirements:
- Remove Python2 constraints - only Python3 is now supported
- No longer upgrade `pip` - this was only required for Python2 to ensure newer build and install functionality
- Hide pip update warnings in the logs with `PIP_NO_PYTHON_VERSION_WARNING`
- Use the packaged `python3-venv` rather than the `virtualenv` module
Using the packaged modules avoids warnings in the CI logs such as:
```
2025-02-06T21:19:48.6636024Z WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want …
```

Python MapScript updates

---

.github/workflows/cppcheck.yml
scripts/cppcheck.sh

- Updates the CI runner to ubuntu-latest
- Moves the actual cppcheck to a script run through Docker with a fixed image of ubuntu:20.04
This reduces the risk of breaking CI due to the vagaries and timelines of GitHub such as the following change:
> We will soon start the deprecation process for Ubuntu 20.04. While the image is being deprecated, you may experience longer queue times during peak usage hours. Deprecation will begin on 2025-02-01 and the image will be fully unsupported by 2025-04-01.
From https://github.com/actions/runner-images/issues/11101

CI: Run cppcheck using Docker

---

.github/workflows/build-mapscript-python.yml
.github/workflows/build.yml
ci/ubuntu/setup.sh
scripts/build-mapscript-python.sh

As with #7224 run the build-mapscript-python workflow using Docker. Also switch the main build to use `ubuntu-latest` (as there are modifications to the shared `setup.sh` script). 
Quite a few hurdles to overcome to get this working, and unsure why moving to a shell script caused some parts of `setup.sh` to stop working. `pyenv` is also tricky to configure (and the approach seems to have changed a few times over the years). 
A couple of notes for reference. The following error ` docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: exec: "/home/runner/work/mapserver/mapserver/scripts/build-mapscript-python.sh": permission denied: …

CI: Update build-mapscript-python to use Docker

---

src/mappostgis.cpp

msPostGISReadShape(): fix crash if returned geometry is NULL

---

ci/ubuntu/setup.sh

Contrary to what I wrote in #7228 - the CI failures were caused by a *downgrade* of GDAL and PROJ. The `ubuntu-20.04` (Focal) packages were removed from `ubuntugis-unstable` which caused the CI to get older builds of GDAL and PROJ from `http://archive.ubuntu.com/ubuntu focal/`. 
CI was failing as GDAL was changed from 3.4.3 to 3.0.4 and PROJ from 8.2.0 to 6.3.1. 
This pull requests (temporarily) switches from `ubuntugis/ubuntugis-unstable` to `ubuntugis/ppa`  (ubuntugis-stable) to get the CI passing again.

CI: Update (temporarily) to ubuntugis-stable

---

msautotest/pymod/mstestlib.py

The recent change 64a706f6f598e8bc912a2c0713cc4228e8805f44 introduced a severe regression on msautotest.
At the moment it would not detect changes in test output in many cases. You can test this by changing any textual expected result file.
For example take `msautotest/config/expected/missing_conf.txt`, rewrite the expected error message, run the test and see how it still succeed.
The issue is how the comparison result is currently interpreted
https://github.com/MapServer/MapServer/blob/4121426f071bc0f090f203569cc31bd3feca92b9/msautotest/pymod/mstestlib.py#L725-L742
With the removal of the extra `ignore_comparison_result` parameter the first if block is always considered. The compare result is either `== "match"` and the test successful or `!= "match"` and the difference ignored and the …

msautotest: Fix interpretation of test output comparison in mstestlib

---

.github/workflows/start.sh
CMakeLists.txt

As reported in [Debian Bug #1101239](https://bugs.debian.org/1101239), MapServer fails to build with ICU 76 (pulled in via libxml2) which now requires C++17.

 Bump C/C++ standard to 17 for ICU 76.

---

Vagrantfile
scripts/vagrant/virtualbox-fix.sh

The default 2GB of RAM for vagrant makes builds very slow. It can be overwritten with environment variables, but making the default 4GB makes it run through msautotests much faster. 
The virtualbox-fix.sh no longer seems necessary (or have an effect). VBoxGuestAdditions is now up to version 7.x now (4.3 is referred to in the script). 
Fix added to make it fully automated in https://github.com/MapServer/MapServer/commit/29be7f091310cb7a2f343e15e344dd3e21e352ed

Increase default memory for vagrant and remove legacy fix

---

msautotest/misc/expected/browse.html
msautotest/misc/expected/wms_projected.html
msautotest/misc/expected/wms_projected_extra.html
msautotest/misc/openlayers.map
src/maptemplate.c

The OpenLayers template added in #7218 works fine when a request is made using one of the built-in OpenLayers projections - EPSG:4326 or EPSG:3857, however for other projections when using WMS requests and `&FORMAT=application/openlayers` OpenLayers throws an error:
```js
TypeError: Cannot read properties of null (reading 'getAxisOrientation')
const axisOrientation = projection.getAxisOrientation();
```
This PR adds an additional JS check to prevent this error, by ensuring the code is registered with OpenLayers. As the map only shows layers from MapServer the actual projections don't need to have any further details (which would get very complicated and require proj4js to be included and fulll PROJ definitions to be sent back).
The check is as follows:
```js
if (!ol.proj.get('EPSG:2157')) …
```

Update OpenLayers version and support non-built-in projections

---

src/mapmssql2008.c

This PR will only use the SQLWCHAR versions of the ODBC API when on Windows and ICONV is present. With this change I was able to connect successfully from an Ubuntu machine with MapServer installed to a SQL Server 19 database with MapServer. 
Without this change there was an initial error `'[unixODBC][Driver Manager]Data source name not found and no default driver specified'` as the connection string was getting corrupted. 
Without the other changes the SQL statements themselves were getting corrupted, and the SQL Server Profiler showed SQL requests similar to those below:
```
SLC GO]'em,ovr(aca(6,[betd)'d RM
(
EET*FO do.RI_EWR_EMN_IE
)
stlWEEGO.TnescsGoer:SGoFoTx(PLGN(7214 1312,1956586.8892. 6053,7214 6053,7214 1312)'25)   
```
With this PR it is now possible to connect successfully: …

Allow mssql driver to be used on Linux

---

src/maptemplate.c

When using the [OpenLayers output](https://mapserver.org/cgi/openlayers.html) for a WMS requests (by adding `&FORMAT=application/openlayers`), the "ows_onlineresource" is used as part of the OpenLayers template:
https://github.com/MapServer/MapServer/blob/e6eba841ae2c4fc92061ac11fa01c7595cbb492d/src/maptemplate.c#L102
However, currently only `ows_onlineresource` is checked for in the metadata. This PR also checks for the  `wms_onlineresource` WEB METADATA key.

Check wms_onlineresource for OpenLayers output

---

src/mapogr.cpp

In certain cases MS would end up in a endless recursion, with the following stack:
`msOGRFileReadTile` - fetch next tile 
-- `msOgrFileWhichShapes` - bbox filter 
----  `msOgrInitItems` - reload items
------- `msOGRFileReadTile` - fetch tile...
To avoid this, I moved `msOgrInitItems` out of the function. 
In my case, it was triggered by a WFS GetFeature request to a tileindex layer, where the data was GPKG and the tileindex itself was a shapefile.
I made an attempt at recreating the issue from the existing [auto test](https://github.com/MapServer/MapServer/blob/main/msautotest/wxs/wfs_ogr_tileindex_of_shp.map) but did not get that far at the moment. I suspect it would enter the relevant code if a `sortBy`-clause was added to the WFS request in the test. But it threw (unrelated) errors …

Tileindex: Fix vector tileindex infinite recursion

---

msautotest/pymod/mstestlib.py

Fixes
```
Cannot validate XML because SCHEMAS_OPENGIS_NET not found. Run "python ../pymod/xmlvalidate.py -download_ogc_schemas" from msautotest/wxs
Traceback (most recent call last):
File "/home/runner/work/mapserver/mapserver/msautotest/wxs/./run_test.py", line 43, in <module>
mstestlib.get_pytests(os.path.dirname(os.path.abspath(__file__))),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/mapserver/mapserver/msautotest/wxs/../pymod/mstestlib.py", line 536, in get_pytests
if not has_requires(version_info, gdal_version, requires_list):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/mapserver/mapserver/msautotest/wxs/../pymod/mstestlib.py", line 111, in has_requires
if compare_version(gdal_version, …
```

msautotest: fix get_gdal_version() to support GDAL version nickname

---

scripts/vagrant/packages.sh

Avoid calling `apt-get update` twice and remove `apt-get -y upgrade` call. 
Also, no need to force an update of Python packages.

Speed-up vagrant package installation

---

msautotest/pymod/mstestlib.py

Following on from https://github.com/MapServer/MapServer/pull/7317 I ran into a similar issue when using Vagrant.
The GDAL version string was `3.11.3 "Eganville", released 2025/07/12`, and due to the comma raised the following error:
```python
run_test.py:43: in <module>
mstestlib.get_pytests(os.path.dirname(os.path.abspath(__file__))),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../pymod/mstestlib.py:540: in get_pytests
if not has_requires(version_info, gdal_version, requires_list):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../pymod/mstestlib.py:111: in has_requires
if compare_version(gdal_version, item[len("GDAL>=") :]) < 0:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../pymod/mstestlib.py:84: in compare_version
a_x, a_y, a_z = int(a[0]), …
```

msautotest Python GDAL get version fix

---

msautotest/wxs/wms_raster.map
src/mapraster.c

Manual backport of #7333 (original failed: https://github.com/MapServer/MapServer/pull/7333#issuecomment-3347243898). 
* Fix use-after-free error in msDrawRasterLayerLowOpenDataset
* A test case for crash on printing raster debug info

[Backport branch-8-4] Fix use-after-free error in msDrawRasterLayerLowOpenDataset (#7333)
